### PR TITLE
[MS] Fixed sort by style

### LINKED ISSUE #6782: [🏚️ Visual bug] Organization ms-sorter appearance problems
- [ ] The sorter is too small compared to the search field and the button
- [x] The last case is on 2 lines when selected

image

### PR DESCRIPTION
**Pull request by fabienSvtr**
## Describe your changes

image

## Checklist

Before you submit this pull request, please make sure to:

- [ ] Keep changes in the pull request as small as possible
   
- [ ] Ensure the commit history is sanitized
   
- [ ] Give a meaningful title to your PR
- [ ] Describe your changes

closes #6782

### CODE REVIEW

File: client/src/components/core/ms-sorter/MsSorterPopover.vue [hunk 1]
```diff
@@ -19,6 +19,9 @@
       class="sorter-list"
       id="sort-item-list"
     >
+      <ion-label class="sorter-list__title body-sm">
+        {{ $t('FoldersPage.sort.sortBy') }}
```
Comment (Max-7) [inline client/src/components/core/ms-sorter/MsSorterPopover.vue:23]: Should move this translation string, we're in `core`, we shouldn't find a reference to `FoldersPage` here.

**Review by Max-7 — CHANGES_REQUESTED** [review]

**Review by Max-7 — APPROVED** [review]
