### PR TITLE
[PKI] Fix pki_enroll_accept to accept the payload as struct instead of bytes

### LINKED ISSUE #11568: [pki] pass the submit payload as a struct format in pki accept
Current the expose `pki_enroll_accept` to the client expect submit_payload to be provided as bytes. instead we should provide it as a struct form since `pki_enroll_list` will provide struct

_Originally posted by @FirelightFlagboy in https://github.com/Scille/parsec-cloud/pull/11544#discussion_r2495205302_

### PR DESCRIPTION
**Pull request by AureliaDolo**
fix #11568

### CODE REVIEW

File: libparsec/src/client.rs [hunk 1]
```diff
@@ -709,11 +709,9 @@ pub async fn client_pki_enrollment_accept(
     enrollment_id: PKIEnrollmentID,
     human_handle: &HumanHandle,
```
Comment (AureliaDolo) [inline libparsec/src/client.rs:710]: Already in the payload : remove

File: libparsec/crates/client/src/client/mod.rs
Comment (FirelightFlagboy) [inline libparsec/crates/client/src/client/mod.rs:1]: **issue:** I assumed that the correct human_handle is provided by the payload that is modified.

We should not modify the payload but keep the additional human_handle

Comment (AureliaDolo) [reply libparsec/crates/client/src/client/mod.rs:1]: Right ! I forgot that the greeter can modify the human handle

**Review by FirelightFlagboy — APPROVED** [review]
