### PR TITLE
[MS] fix HomePage animation states

### LINKED ISSUE #6784: [MS] HomePage back to organization list animation bug
https://github.com/Scille/parsec-cloud/assets/19772607/8d5658af-0144-4854-9465-56ca028037e7

### LINKED ISSUE #6857: [MS] From create org modal to workspace page animation bug
⚠ Bug can be reproduced only with **Password authentification** method.

https://github.com/Scille/parsec-cloud/assets/81075511/7d73ea69-f161-4966-bd04-812078f7d1ee

### PR DESCRIPTION
**Pull request by NicoTuxx**
closes #6857

### CODE REVIEW

**Review by fabienSvtr — APPROVED** [review]

File: client/src/views/home/HomePage.vue [hunk 1]
```diff
@@ -184,10 +181,6 @@ async function openJoinByLinkModal(link: string): Promise<void> {
   await modal.dismiss();
   hotkeyManager.enableGroup(Groups.Home);
   if (result.role === MsModalResult.Confirm) {
-    if (result.data.device.ty === DeviceFileType.Password) {
```
Comment (Max-7) [inline client/src/views/home/HomePage.vue:187]: This is also done after creating the org, does it also causes problems there?

**Review by Max-7 — CHANGES_REQUESTED** [review]

**Review by Max-7 — APPROVED** [review]
