### PR TITLE
[MS] Update invoice status for Custom Order

### LINKED ISSUE #10313: [🐛 | Bug]: Wrong icon color for the 'Download' button
### Parsec version tested on:

3.4.0 rc1

### Platforms tested on:

Windows, MacOS

### Bug description:

The svg icon isn't the right color

### Relevant output:

Image

### LINKED ISSUE #10459: [MS] (Customer area | Custom order) Invoice status is showing `void` in some cases
`InvoiceStatus` comes from Sellsy, but it is only informative and is decorrelated from `CustomOrderStatus`.
We should display the invoice status by the CustomOrderStatus and only with Paid or To be paid.

Image

### PR DESCRIPTION
**Pull request by fabienSvtr**
## Describe your changes

image

## Checklist

Before you submit this pull request, please make sure to:

- [ ] Keep changes in the pull request as small as possible
   
- [ ] Ensure the commit history is sanitized
   
- [ ] Give a meaningful title to your PR
- [ ] Describe your changes
   
- [ ] Link any related issue in the description
   
- [ ] Link any dependent pull request in the description

closes #10459, closes #10313

### CODE REVIEW

File: client/src/components/client-area/invoices/InvoicesListItem.vue [hunk 1]
```diff
@@ -33,12 +33,25 @@
       </ion-text>
     </template>
     <ion-text class="invoices-year-content-list-item__data invoices-status">
-      <span
-        class="badge-status body-sm"
-        :class="invoice.getStatus()"
-      >
-        {{ $msTranslate(getInvoiceStatusTranslationKey(invoice.getStatus())) }}
-      </span>
+      <template v-if="invoice.getType() === InvoiceType.Sellsy && invoice.getDueAmount !== undefined">
```
Comment (NicoTuxx) [inline client/src/components/client-area/invoices/InvoicesListItem.vue]: `invoice.getDueAmount` will never be undefined since it's a function.

File: client/src/components/client-area/invoices/InvoicesListItem.vue [hunk 2]
```diff
@@ -33,12 +33,25 @@
...
+        <span
+          class="badge-status body-sm"
+          :class="{
+            paid: invoice.getDueAmount() > 0,
+            toPaid: invoice.getDueAmount() === 0,
+          }"
+        >
+          {{ $msTranslate(getInvoiceInvoiceStep()) }}
```
Comment (NicoTuxx) [inline client/src/components/client-area/invoices/InvoicesListItem.vue]: Why InvoiceInvoiceStep? maybe we could simplify this name.

File: client/src/components/client-area/invoices/InvoicesListItem.vue [hunk 3]
```diff
@@ -59,11 +72,21 @@ import { Invoice, InvoiceType, SellsyInvoice } from '@/services/bms';
...
 import { IonItem, IonText } from '@ionic/vue';
-import { MsImage, DownloadIcon, I18n } from 'megashark-lib';
+import { MsImage, DownloadIcon, I18n, Translatable } from 'megashark-lib';
 
-defineProps<{
+const props = defineProps<{
   invoice: Invoice;
 }>();
+
+function getInvoiceInvoiceStep(): Translatable {
```
Comment (NicoTuxx) [inline client/src/components/client-area/invoices/InvoicesListItem.vue]: same here for the name.

File: client/src/components/client-area/invoices/InvoicesListItem.vue [hunk 4]
```diff
@@ -59,11 +72,21 @@ import { Invoice, InvoiceType, SellsyInvoice } from '@/services/bms';
...
+  if (props.invoice.getDueAmount === undefined) {
+    return 'clientArea.invoices.status.unknown';
+  } else if (props.invoice.getDueAmount() > 0) {
+    return 'clientArea.invoices.status.paid';
+  } else {
+    return 'clientArea.invoices.status.toPay';
```
Comment (NicoTuxx) [inline client/src/components/client-area/invoices/InvoicesListItem.vue]: sometimes you use `toPay` or `toPaid`, choose only one for coherence.

File: client/src/components/client-area/invoices/InvoicesListItem.vue [hunk 5]
```diff
@@ -33,12 +33,25 @@
...
+            toPaid: invoice.getDueAmount() === 0,
+          }"
+        >
+          {{ $msTranslate(getInvoiceInvoiceStep()) }}
+        </span>
+      </template>
+      <template v-if="invoice.getType() === InvoiceType.Stripe">
+        <span
+          class="badge-status body-sm"
+          :class="invoice.getStatus() === 'paid' ? 'paid' : 'toPaid'"
```
Comment (NicoTuxx) [inline client/src/components/client-area/invoices/InvoicesListItem.vue]: Is there more cases than paid and 'toPaid' for stripe?

File: client/src/components/client-area/invoices/InvoicesListItem.vue (hunk 2 above)
Comment (fabienSvtr) [reply client/src/components/client-area/invoices/InvoicesListItem.vue]: Yes sure, `getStatusInvoiceStep` is better

**Comment by NicoTuxx** [comment]
`toPaid` does not make sense, rename it `toBePaid`
