### PR TITLE
Make parsec use $HOME/.config as the base configuration directory for the snap package

### LINKED ISSUE #8464: [🐛 | Bug]: If snap user remove the snap they lost their devices
### Parsec version tested on:

3.0.0

### Platforms tested on:

Linux

### Bug description:

Repro: 

> [!Caution]
> Be mindfull when trying to reproduce the bug, you will lose your devices!

1. Install parsec using snap:
   ```shell
   snap install parsec --channel=v3
   ```

2. Create a trial organization
3. Remove parsec
   ```shell
   snap remove parsec
   ```
4. Re-install parsec using snap (see step 1)
5. Observe your trial device no longer exist

## Explanation

On snap, the devices are stored under `~/snap/parsec/{version}/.config/parsec3/libparsec/devices`.

Upon removal of the snap, the folder `~/snap/parsec/{version}` will be removed alongside it.

### Relevant output:

_No response_

### PR DESCRIPTION
**Pull request by FirelightFlagboy**
Also migrate previous devices located in snap user data

Closes #8464

### CODE REVIEW

File: client/electron/scripts/snap_migrate_devices_from_snap_user_data.sh [hunk 1]
```diff
@@ -0,0 +1,13 @@
+#!/bin/bash
+
```
Comment (mmmarcos) [inline client/electron/scripts/snap_migrate_devices_from_snap_user_data.sh:2]:
```suggestion
# This scripts copies device files (.keys) from the legacy device directory (based on $HOME/snap)
# to the new device directory (based on $HOME/.config)

```

File: newsfragments/8464.bugfix.rst [hunk 2]
```diff
@@ -0,0 +1,2 @@
+Fix for Linux snap's users where devices are removed when the snap is removed (``snap remove parsec``).
+The fix include set ``PARSEC_BASE_CONFIG_DIR`` to ``$HOME/.config`` and have a script that copy devices present in snap user data to the new location.
```
Comment (mmmarcos) [inline newsfragments/8464.bugfix.rst:2]: The migration script would be executed on `install` or `refresh`, but not on `remove` is that so?
I would rephrase it a little bit:
```suggestion
Fix for lost devices when parsec snap is removed: devices are now stored in ``$HOME/.config`` and are independent from snap. Existing devices are migrated.
```

**Review by mmmarcos — CHANGES_REQUESTED** [review]

**Review by mmmarcos — APPROVED** [review]
LGTM
