### PR TITLE
[MS] Improve settings list and some design tweaks

### LINKED ISSUE #10912: [MS] replace star icon for pin action by a pin icon
A star is more for favorites. 

Image

Image

### LINKED ISSUE #10952: Missing scroll bar in settings (not connected to an organization)
### Parsec version

v3.5.0-a.5

### Which platform(s) you have observed the problem

- [ ] Any
- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Web

### Bug description

https://github.com/user-attachments/assets/16095270-13f9-46a8-bb42-4ee498998c70

Edit: the last 3 seconds of the video are broken that did not look that way IRL

### Reproduction steps

```bash
Go to settings before logging into an organization, on a smaller display.
```

### Relevant output:

_No response_

### LINKED ISSUE #10954: Cannot go back out of "archive" modal
Image

Clicking on the background does nothing

### PR DESCRIPTION
**Pull request by fabienSvtr**
https://github.com/user-attachments/assets/a160821f-1f35-4878-b621-6a8538e05f26

https://github.com/user-attachments/assets/3ab54925-f0b7-4450-8926-40444155a21c

closes #10954,
closes #10952,
closes #10912

### CODE REVIEW

File: client/src/components/settings/SettingsList.vue [hunk 1]
```diff
@@ -3,113 +3,149 @@
...
-          fill="clear"
-          class="see-logs-button"
+      <div class="settings-list-group">
+        <ion-text class="title-large settings-list-group__title title-h3">
+          {{ $msTranslate('SettingsModal.titles.display') }}
+        </ion-text>
+        <!-- change lang -->
+        <settings-option
+          class="settings-list__item"
+          :title="'SettingsModal.language.label'"
```
Comment (Max-7) [inline client/src/components/settings/SettingsList.vue]: You can remove all the `:title="'Text'"` while you're at it. `title="SettingsModal.language.label"` is cleaner.

File: client/src/components/settings/SettingsList.vue [hunk 2]
```diff
@@ -3,113 +3,149 @@
...
-        <ion-toggle v-model="config.meteredConnection" />
-      </settings-option>
-      <!-- skip file viewers -->
-      <settings-option
+        <ion-text class="title-large settings-list-group__title title-h3">
+          {{ $msTranslate('SettingsModal.titles.account') }}
+        </ion-text>
+        <!-- open config dir -->
+        <settings-option
+          v-if="isDesktop() && !usesTestbed()"
```
Comment (Max-7) [inline client/src/components/settings/SettingsList.vue:94]: This is not linked to the account in any way.

File: client/src/locales/en-US.json [hunk 3]
```diff
@@ -933,8 +939,8 @@
         "organization": "Organization",
         "workspaces": "My workspaces",
         "recentWorkspaces": "Recent",
-        "favorites": "Pinned",
-        "noFavorites": "No pinned workspaces",
+        "favorites": "Favorites",
```
Comment (Max-7) [inline client/src/locales/en-US.json]: Didn't we change "Favorites" for "Pinned" like two months ago? Why changing it back? What does this have to do with this PR?

**Review by Max-7 — CHANGES_REQUESTED** [review]
