### PR TITLE
fix(pki): Missing sign algo in pki accept

### LINKED ISSUE #11537: Missing signature algorithm in pki enrollment accept
https://github.com/Scille/parsec-cloud/blob/0040a244bd4f4d5e2a75e101a079c5ff0b5b1e20/libparsec/crates/protocol/schema/authenticated_cmds/pki_enrollment_accept.json5#L19-L23

### PR DESCRIPTION
**Pull request by FirelightFlagboy**
Closes #11537

### CODE REVIEW

File: server/parsec/components/postgresql/migrations/0017_pki_enrollment_accept_payload_signature_algorithm.sql [hunk 1]
```diff
@@ -0,0 +1,12 @@
+-- Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS
```
Comment (touilleMan) [inline server/parsec/components/postgresql/migrations/0017_pki_enrollment_accept_payload_signature_algorithm.sql]: I think we should merge this migration with the previous one (i.e. `0016_pki_enrollment_submit_payload_signature_algorithm.sql`) since:
- migration 0016 is not yet in production
- both migrations basically deal with the same thing (i.e. adding `PKI_SIGNATURE_ALGORITHM` type and using it)

File: server/parsec/components/postgresql/migrations/datamodel.sql [hunk 2]
```diff
@@ -432,10 +432,13 @@ CREATE TYPE enrollment_state AS ENUM (
     'CANCELLED'
 );
 
+CREATE TYPE pki_signature_algorithm AS ENUM ('RSASSA_PSS_SHA256');
+
 CREATE TYPE pki_enrollment_info_accepted AS (
     accepted_on TIMESTAMPTZ,
     accepter_der_x509_certificate BYTEA,
     accept_payload_signature BYTEA,
+    accept_payload_signature_algorithm PKI_SIGNATURE_ALGORITHM,
```
Comment (touilleMan) [inline server/parsec/components/postgresql/migrations/datamodel.sql]: Fields added in a migration must be added at the end of the table (otherwise migration tests will fail), also should add a `-- Added in migration 0016` comment before the added field

File: server/parsec/components/postgresql/migrations/0017_pki_enrollment_accept_payload_signature_algorithm.sql (hunk 1 above)
Comment (FirelightFlagboy) [reply server/parsec/components/postgresql/migrations/0017_pki_enrollment_accept_payload_signature_algorithm.sql]: done

File: server/parsec/components/postgresql/migrations/datamodel.sql (hunk 2 above)
Comment (FirelightFlagboy) [reply server/parsec/components/postgresql/migrations/datamodel.sql]: done

File: server/parsec/components/postgresql/migrations/0016_pki_enrollment_add_sign_algo.sql [hunk 3]
```diff
@@ -12,3 +13,4 @@ CREATE TYPE pki_signature_algorithm AS ENUM ('RSASSA_PSS_SHA256');
 -- no row since it was never used so far (it has been kept from Parsec v2 in
 -- prevision of a future support of PKI enrollment).
 ALTER TABLE pki_enrollment ADD submit_payload_signature_algorithm PKI_SIGNATURE_ALGORITHM NOT NULL;
+ALTER TYPE pki_enrollment_info_accepted ADD ATTRIBUTE accept_payload_signature_algorithm PKI_SIGNATURE_ALGORITHM;
```
Comment (touilleMan) [inline server/parsec/components/postgresql/migrations/0016_pki_enrollment_add_sign_algo.sql]: The field doesn't need to be marked as `NOT NULL` ?

File: server/parsec/components/postgresql/pki_info.py [hunk 4]
```diff
@@ -110,9 +111,12 @@ async def pki_info(
                     "accepter_der_x509_certificate": bytes() as accepter_der_x509_certificate,
                     "accept_payload_signature": bytes() as accept_payload_signature,
                     "accept_payload": bytes() as accept_payload,
+                    "accept_payload_signature_algorithm": str() as raw_accept_payload_signature_algorithm,
                     **rest,
                 } if not rest:
-                    pass
+                    _accept_payload_signature_algorithm = PkiSignatureAlgorithm.from_str(
```
Comment (touilleMan) [inline server/parsec/components/postgresql/pki_info.py:117]: Not used ? the next PR will introduced this field in `pki_enrollement_info` I guess ?

Comment (FirelightFlagboy) [reply server/parsec/components/postgresql/pki_info.py:117]: Yes
