### PR TITLE
[MS] Added support for custom branding

### LINKED ISSUE #10500: Dynamic management of resources
The app should be able to load resources dynamically (used for custom branding).

Using the logo as example:

- the app should first try to load the logo from a server (defined in config)
- if it fails, it should try to load the image for a folder (defined in config, with default)
- if it fails, it should display the default logo

### PR DESCRIPTION
**Pull request by Max-7**
Closes #10500 

This adds the support for custom branding.
Files can be put inside `public/custom` for web, or `electron/custom` for electron, and they will be used if available. For now, it only uses a few files defined in `resourcesManager.ts`. Texts can be fully replaced with `en_US.json` and `fr_FR.json`.

- [X] Keep changes in the pull request as small as possible
- [X] Ensure the commit history is sanitized
- [X] Give a meaningful title to your PR
- [X] Describe your changes
- [X] Link any related issue in the description

### CODE REVIEW

File: client/src/main.ts [hunk 1]
```diff
@@ -674,6 +692,7 @@ declare global {
       seeInExplorer: (path: string) => void;
       getLogs: () => Promise<Array<string>>;
       initError: (error?: string) => void;
+      readCustomFile: (ffile: string) => Promise<ArrayBuffer | undefined>;
```
Comment (Ironicbay) [inline client/src/main.ts]: typo on `file` argument

**Review by NicoTuxx — APPROVED** [review]
