### PR TITLE
Fix url parsing with splitted scheme

### LINKED ISSUE #9316: panic: internal error: entered unreachable code: scheme can only be http or https
Sentry Issue: [PARSEC3-LIBPARSEC-M](https://scille.sentry.io/issues/6209884300/?referrer=github_integration)

```
panic: internal error: entered unreachable code: scheme can only be http or https
  ?, in napi_register_module_v1
  ?, in napi_register_module_v1
  ?, in napi_register_module_v1
  ?, in napi_register_module_v1
  ?, in napi_register_module_v1
...
(80 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by touilleMan**
close #9316

### CODE REVIEW

File: libparsec/crates/types/tests/unit/addr.rs [hunk 1]
```diff
@@ -275,7 +298,10 @@ fn addr_with_bad_port(testbed: &dyn Testbed, #[values("NaN", "999999")] bad_port
 }
 
 #[apply(all_addr)]
-fn addr_with_bad_scheme(testbed: &dyn Testbed, #[values("xxx", "http", "https")] bad_scheme: &str) {
+fn addr_with_bad_scheme(
+    testbed: &dyn Testbed,
+    #[values("xxx", "http", "https", "parsec4", "parsec", "parsec3x")] bad_scheme: &str,
```
Comment (FirelightFlagboy) [inline libparsec/crates/types/tests/unit/addr.rs:303]:
```suggestion
    #[values("xxx", "http", "https", "parsec4", "parsec", "parsec3x", "par\snec3")] bad_scheme: &str,
```

So the example `par\nsec3` is tested

**Review by FirelightFlagboy — APPROVED** [review]
Should this PR be backported?

File: libparsec/crates/types/tests/unit/addr.rs (hunk 1 above)
Comment (touilleMan) [reply libparsec/crates/types/tests/unit/addr.rs:303]: This doesn't work since `par\nsec3` will be stripped of `\n` when the url is parsed, so the actual scheme becomes `parsec3`

Comment (FirelightFlagboy) [reply libparsec/crates/types/tests/unit/addr.rs:303]: What I want is tested by `good_addr_with_noise_trimmed_by_url_parser`, So all good

**Comment by touilleMan** [comment]
> Should this PR be backported?

I would say it's not worth the trouble since it's a rather peculiar bug, but I let @mmmarcos decide ;-)
