### PR TITLE
[MS] Fix cross-platform tray icon

### LINKED ISSUE #6922: Change icon depending tray and OS

### PR DESCRIPTION
**Pull request by Ironicbay**
Closes #6922

### CODE REVIEW

File: client/electron/src/setup.ts [hunk 1]
```diff
@@ -153,15 +153,31 @@ export class ElectronCapacitorApp {
...
+        trayIconName = 'iconTemplate.png';
+        break;
+      case 'linux':
+        trayIconName = '512x512.png';
+        break;
+      default:
+        trayIconName = 'icon.png';
+    }
+
+    const appIcon = nativeImage.createFromPath(join(app.getAppPath(), 'assets', process.platform === 'linux' ? '512x512.png' : 'icon.png'));
```
Comment (Max-7) [inline client/electron/src/setup.ts:168]: What's the point of this ternary if you have a switch/case before?

**Review by Max-7 — CHANGES_REQUESTED** [review]

**Review by Max-7 — APPROVED** [review]
