### PR TITLE
[MS] Responsive file folder table

### LINKED ISSUE #11200: [MS] Options column in the file list is not visible when resizing
### Parsec version

3.5

### Which platform(s) you have observed the problem

- [x] Any
- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Web

### Bug description

When resizing the page, the option column become invisible.

### Reproduction steps

```bash
1. Resize the page after loading some files
```

### Relevant output:

(Yellow column)
Image

### PR DESCRIPTION
**Pull request by fabienSvtr**
The PR should redefined how the file folder responsive is managed. 

This PR includes:
- Global management of the size of each column using percentages to improve responsive rendering.
- Updates of all tests including modified columns.
- Option column is always visible (dot options: `•••`)

https://github.com/user-attachments/assets/7cc9ab31-2ad6-4dcc-92bb-f2abf3dad45d

closes #11200

### CODE REVIEW

File: client/src/components/files/explorer/FileListItemProcessing.vue [hunk 1]
```diff
@@ -84,6 +87,7 @@ const { isLargeDisplay } = useWindowSize();
 
 onMounted(async () => {
   const result = await getClientInfo();
+  console.log(result);
```
Comment (Max-7) [inline client/src/components/files/explorer/FileListItemProcessing.vue]: Remove

File: client/tests/e2e/helpers/utils.ts [hunk 2]
```diff
@@ -163,7 +163,7 @@ export async function openFileType(
   const entries = documentsPage.locator('.folder-container').locator('.file-list-item');
 
   for (const entry of await entries.all()) {
-    const entryName = (await entry.locator('.file-name').locator('.file-name__label').textContent()) ?? '';
+    const entryName = (await entry.locator('.file-name').locator('..label-name').textContent()) ?? '';
```
Comment (Max-7) [inline client/tests/e2e/helpers/utils.ts]: Two `..`
