### PR TITLE
[MS] Filtered menu and header actions depending on profile and role

### LINKED ISSUE #11232: [GUI] Externals can create workspaces
### Parsec version

3.5.0

### Which platform(s) you have observed the problem

- [ ] Any
- [ ] macOS
- [ ] Linux
- [x] Windows
- [x] Web

### Bug description

On Parsec client (GUI), outsider can create workspaces but the content is not synchronized.
Condition `v-show="clientProfile != UserProfile.Outsider"` seems not working.

### Reproduction steps

```bash
1. Create an outsider user
2. Connect with outsider profile
3. Create a workspace
```

### Relevant output:

https://github.com/user-attachments/assets/f46e4fb2-d219-4cda-8191-d27ccc3e9c27

### PR DESCRIPTION
**Pull request by Ironicbay**
Closes #11232 
- Removed infos about invitations in the organisation page for `Standard` users
- Removed access to organisation page for `External` users in small display
- Filtered workspace contextual menu options for `Reader` role
- Removed the option to create a workspace for `External` users
- Added tests for these changes

### CODE REVIEW

File: client/src/views/workspaces/WorkspacesPage.vue [hunk 1]
```diff
@@ -510,6 +510,10 @@ function onMsSorterChange(event: MsSorterChangeEvent): void {
 }
 
 async function createWorkspace(name: WorkspaceName): Promise<void> {
+  // Externals shouldn't be able to access here, but putting this as safety
```
Comment (Max-7) [inline client/src/views/workspaces/WorkspacesPage.vue:513]: What's the behavior of `parsecCreateWorkspace` when the user is an outsider? Does it works or does it return an error?
- If it returns an error, then that check is counter-productive: we should never get here, but if we do, it's better to display an error rather than nothing happening when the user presses the button.
- If it works it's all good.

Comment (Ironicbay) [reply client/src/views/workspaces/WorkspacesPage.vue:513]: Yes there's no restriction for externals to create a workspace. On master & latest version, they can create and browse local workspaces that won't be synced with the server.

File: client/tests/e2e/specs/organization_information.spec.ts [hunk 2]
```diff
@@ -49,6 +51,50 @@ for (const displaySize of [DisplaySize.Large, DisplaySize.Small]) {
...
+    await expect(configContainer.locator('.info-list-item').locator('.info-list-item__title')).toHaveText([
+      'External profile',
+      'User limit (excluding users with External profile)',
+      'Server address',
+    ]);
+    await expect(configContainer.locator('.info-list-item').nth(0).locator('.info-list-item__value')).toHaveText(['Enabled']);
+    await expect(configContainer.locator('.info-list-item').nth(1).locator('.info-list-item__value')).toHaveText(['Unlimited']);
+    await expect(configContainer.locator('.info-list-item').nth(2).locator('.server-address-value__text')).toHaveText(/^parsec3:\/\/.+$/);
+
+    await expect(usersContainer.locator('.users-list-item').nth(0).locator('.users-list-item__title')).toHaveText('3');
```
Comment (Max-7) [inline client/tests/e2e/specs/organization_information.spec.ts]: Creating intermediate variables can make this a little clearer.

File: client/tests/e2e/specs/organization_information.spec.ts [hunk 3]
```diff
@@ -49,6 +51,50 @@ for (const displaySize of [DisplaySize.Large, DisplaySize.Small]) {
...
+    const storageContainer = container.locator('.organization-storage');
+    const emailInvitationCard = usersContainer.locator('.invitation-card-list-item').nth(0);
+    const PkiRequestCard = usersContainer.locator('.invitation-card-list-item').nth(1);
+    await usersContainer.locator('#invitations-button').isVisible();
+
+    if (displaySize === DisplaySize.Small) {
+      await organizationPageStandard.setDisplaySize(DisplaySize.Small);
+    }
+
+    await expect(emailInvitationCard).not.toBeVisible();
```
Comment (Max-7) [inline client/tests/e2e/specs/organization_information.spec.ts]: I think using `toBeHidden` is better. I dont really know how this works, but I would guess that it executes the `toBeVisible`, it tries to check for the full timeout (5s by default), and then applies the not. Which means the expect always take the full 5s.

File: client/tests/e2e/specs/organization_information.spec.ts [hunk 4]
```diff
@@ -49,6 +51,50 @@ for (const displaySize of [DisplaySize.Large, DisplaySize.Small]) {
     await expect(storageContainer.locator('.storage-list-item__value').nth(1)).toHaveText(/^\d+(\.\d{2})? (B|KB|MB)$/);
   });
 
+  msTest(`Org info default state on ${displaySize} display on standard user`, async ({ organizationPageStandard }) => {
```
Comment (Max-7) [inline client/tests/e2e/specs/organization_information.spec.ts:55]: Do we check somewhere that the org page is not available as an external?
