### PR TITLE
[MS] Fix bug: File upload item

### LINKED ISSUE #6281: [🐛 Bug] Display of uploading item
Image

### PR DESCRIPTION
**Pull request by fabienSvtr**
## Describe your changes

image

## Checklist

Before you submit this pull request, please make sure to:

- [x] Keep changes in the pull request as small as possible
   
- [x] Ensure the commit history is sanitized
   
- [x] Give a meaningful title to your PR
- [x] Describe your changes
   
- [x] Link any related issue in the description
   
- [x] Link any dependent pull request in the description

closes #6281

### CODE REVIEW

File: client/src/services/importManager.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { wait } from '@/parsec/internals';
 import { Mutex } from 'async-mutex';
 import { v4 as uuid4 } from 'uuid';
 
-const MAX_SIMULTANEOUS_IMPORT_JOBS = 2;
+const MAX_SIMULTANEOUS_IMPORT_JOBS = 0;
```
Comment (Max-7) [inline client/src/services/importManager.ts:8]: Nop!

**Review by Max-7 — CHANGES_REQUESTED** [review]

File: client/src/services/importManager.ts (hunk 1 above)
Comment (fabienSvtr) [reply client/src/services/importManager.ts]: It was for testing, I put it back
