### PR TITLE
[MS] Client Area Style Miscellaneous (Saas only)

### LINKED ISSUE #10342: [🐛 | Bug]: Bad alignment on client area invoices page
### Parsec version tested on:

3.4.0-rc2

### Platforms tested on:

MacOS

### Bug description:

Depending on date and organization lengths
Image

### Relevant output:

_No response_

### LINKED ISSUE #11998: Responsive on Client area (Saas)
### What you would like to accomplish

The user can use the client area with after resizing (small size) his browser.

### How the feature should work

Simply reduce the size of the page.

### Describe alternatives you have considered

_No response_

### PR DESCRIPTION
**Pull request by fabienSvtr**
### What's included:
- Dashboard responsive
- Invoices page responsive (scrollable table)
- Payment methods responsive
- Billing page (responsive + Additional info field not shown if empty)
- Profile header (according to Parsec client)
- My profile page responsive
- Sidebar:
  - Hidden in SmallDisplay
  - Bigger button 
  - Click on button close menu
  - Toggle menu button

https://github.com/user-attachments/assets/7b32f0d6-cde6-492f-a891-5b5d99efa518

closes #10342, closes #11998

### CODE REVIEW

File: client/src/views/client-area/ClientAreaHeader.vue [hunk 1]
```diff
@@ -1,50 +1,82 @@
...
+        <!-- icon visible when menu is hidden -->
+        <ms-image
+          v-if="!isMobile() && isLargeDisplay"
+          slot="start"
+          id="trigger-toggle-menu-button"
+          class="topbar-button__item"
+          @click="isSidebarMenuVisible ? hideSidebarMenu() : resetSidebarMenu()"
+          :image="SidebarToggle"
         />
+        <ion-menu-toggle v-if="!isMobile() && isSmallDisplay">
```
Comment (Ironicbay) [inline client/src/views/client-area/ClientAreaHeader.vue]: Why `!isMobile()`? Wouldn't we want this toggle on mobile as well?

File: client/src/views/client-area/statistics/StatisticsPage.vue
Comment (Ironicbay) [inline client/src/views/client-area/statistics/StatisticsPage.vue:1]: After selecting an organization on the statistics page, there's no indication of it in small display (it's displayed in the sidebar on large display).
I would either add the organization name somewhere visible like below the header, or add the switch organization popover somewhere in the page. But as I specified in my first comment, the organization-specific statistics page is not done yet

File: client/src/views/client-area/statistics/StatisticsPage.vue [hunk 2]
```diff
@@ -357,6 +365,12 @@ function getIncludedData(): CircleProgressData {
   };
 }
 
+const filteredOrganizations = computed(() =>
+  searchQuery.value.trim()
+    ? props.organizations.filter((org) => org.name.toLowerCase().includes(searchQuery.value.toLowerCase().trim()))
+    : props.organizations,
+);
```
Comment (Ironicbay) [inline client/src/views/client-area/statistics/StatisticsPage.vue]: **suggestion**: Use `if`/`else` rather than ternaries for code clarity.
```suggestion
const filteredOrganizations = computed(() => {
  const query = searchQuery.value.trim();
  if (query) {
    return props.organizations.filter((org) => org.name.toLowerCase().includes(query.toLocaleLowerCase()));
  }
  return props.organizations;
});
```

File: client/src/views/client-area/ClientAreaHeader.vue (hunk 1 above)
Comment (fabienSvtr) [reply client/src/views/client-area/ClientAreaHeader.vue]: Yes, you're right, I updated it.

File: client/src/views/client-area/ClientAreaHeader.vue [hunk 3]
```diff
@@ -1,50 +1,82 @@
...
+              :icon="personCircle"
+              class="avatar-icon"
+            />
+          </div>
+          <div class="text-content">
+            <ion-text class="text-content__name subtitles-normal">{{ getUserName() }}</ion-text>
+          </div>
+        </div>
+      </div>
+    </ion-toolbar>
```
Comment (fabienSvtr) [inline client/src/views/client-area/ClientAreaHeader.vue]:
```suggestion
    </ion-toolbar>
    <div
      class="current-organization"
      v-if="currentOrganization && isSmallDisplay"
    >
      <ion-text class="current-organization__title title-h5">{{ $msTranslate('clientArea.header.organization') }}</ion-text>
      <ion-text
        class="current-organization__name title-h5"
        @click="openOrganizationChoice($event)"
      >
        {{ currentOrganization.name }}
        <ion-icon :icon="sync" />
      </ion-text>
    </div>
```

File: client/src/views/client-area/ClientAreaHeader.vue [hunk 4]
```diff
@@ -1,50 +1,82 @@
...
+  </ion-header>
 </template>
 
 <script setup lang="ts">
-import UserAvatarName from '@/components/users/UserAvatarName.vue';
+import { isMobile } from '@/parsec';
 import { BmsAccessInstance, PersonalInformationResultData } from '@/services/bms';
```
Comment (fabienSvtr) [inline client/src/views/client-area/ClientAreaHeader.vue]:
```suggestion
import OrganizationSwitchClientPopover from '@/components/organizations/OrganizationSwitchClientPopover.vue';
import { BmsAccessInstance, BmsOrganization, PersonalInformationResultData } from '@/services/bms';
```

File: client/src/views/client-area/ClientAreaHeader.vue [hunk 5]
```diff
@@ -1,50 +1,82 @@
...
+import useSidebarMenu from '@/services/sidebarMenu';
 import { ClientAreaPages } from '@/views/client-area/types';
 import { openSettingsModal } from '@/views/settings';
-import { IonIcon, IonText, IonTitle } from '@ionic/vue';
-import { cog } from 'ionicons/icons';
-import { Translatable } from 'megashark-lib';
+import { IonButton, IonHeader, IonIcon, IonMenuToggle, IonText, IonToolbar } from '@ionic/vue';
+import { cog, personCircle } from 'ionicons/icons';
+import { MsImage, SidebarToggle, Translatable, useWindowSize } from 'megashark-lib';
```
Comment (fabienSvtr) [inline client/src/views/client-area/ClientAreaHeader.vue]:
```suggestion
import { IonButton, IonHeader, IonIcon, IonMenuToggle, IonText, IonToolbar, popoverController } from '@ionic/vue';
import { cog, personCircle, sync } from 'ionicons/icons';
import { MsImage, MsModalResult, SidebarToggle, Translatable, useWindowSize } from 'megashark-lib';
```

File: client/src/views/client-area/ClientAreaHeader.vue [hunk 6]
```diff
@@ -71,24 +103,119 @@ function getUserName(): string {
...
-  justify-content: space-around;
+.topbar {
+  --background: var(--parsec-color-light-secondary-white);
+  padding: 1.5rem 2rem 1rem;
   border-bottom: 1px solid var(--parsec-color-light-secondary-disabled);
-}
+  justify-content: space-around;
+
+  @include ms.responsive-breakpoint('sm') {
+    padding: 1.5rem 1.5rem 1rem;
```
Comment (fabienSvtr) [inline client/src/views/client-area/ClientAreaHeader.vue]:
```suggestion
    padding: 0.875rem 1.5rem 0.875rem;
```

File: newsfragments/11998.feature.rst [hunk 7]
```diff
@@ -0,0 +1 @@
+The user can use the customer area on small screens.
```
Comment (Ironicbay) [inline newsfragments/11998.feature.rst]:
```suggestion
Added small screen display mode for the customer area.
```

File: client/src/views/client-area/ClientAreaHeader.vue [hunk 8]
```diff
@@ -1,50 +1,99 @@
...
+          </div>
+          <div class="text-content">
+            <ion-text class="text-content__name subtitles-normal">{{ getUserName() }}</ion-text>
+          </div>
+        </div>
+      </div>
+    </ion-toolbar>
+    <div
+      class="current-organization"
+      v-if="currentOrganization && isSmallDisplay"
```
Comment (Ironicbay) [inline client/src/views/client-area/ClientAreaHeader.vue]: `currentOrganization` has a default value when none is selected so this is `true` at all times. Might as well check for a name since this is what we're displaying, otherwise this text is shown on every page.
```suggestion
      v-if="currentOrganization.name && isSmallDisplay"
```
