### PR TITLE
fix(custom): Fix custom branding detection

### LINKED ISSUE #11029: [Web] Invalid detection of custom branding
### Parsec version

3.5.0-a.6

### Which platform(s) you have observed the problem

- [ ] Any
- [ ] macOS
- [ ] Linux
- [ ] Windows
- [x] Web

### Bug description

The Webapp tries to enable custom branding even tho it's not enabled

### Reproduction steps

```bash
1. Open https://saas-demo-v3-mightyfairy.parsec.cloud/client/account
```

### Relevant output:

```
15:08:30.096 Starting libparsec in shared worker mode index-Bt10mqFf.js:46246:54
15:08:30.096 Client is ready to process events from worker index-Bt10mqFf.js:46270:16
15:08:30.725 Initializing libparsec module web_shared_worker-CO2HOoy1.js:2:49819
15:08:31.440 Done initializing libparsec module web_shared_worker-CO2HOoy1.js:2:49931
15:08:31.440 Worker is ready to process events from client web_shared_worker-CO2HOoy1.js:2:49701
15:08:31.447 [MOCKED-ELECTRON-LOG] Custom branding is enabled, loading resources... index-Bt10mqFf.js:206549:34
15:08:31.625 [MOCKED-ELECTRON-LOG] Failed to retrieve custom resource custom_en-US.json: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data index-Bt10mqFf.js:206549:34
15:08:31.625 [MOCKED-ELECTRON-LOG] Failed to retrieve custom resource custom_fr-FR.json: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data index-Bt10mqFf.js:206549:34
15:08:31.627 Stripe is disabled index-Bt10mqFf.js:206384:37
15:08:31.627 Using mock Stripe service index-Bt10mqFf.js:24685:69
15:08:31.630 Configuring Sentry... index-Bt10mqFf.js:78853:13
15:08:32.077 Using https://bms-dev.parsec.cloud as Parsec BMS index-Bt10mqFf.js:71172:54
15:08:32.173 [MOCKED-ELECTRON-LOG] Error when calling parseParsecAddr: {"error":"Invalid URL","tag":"ParseParsecAddrErrorInvalidUrl"} index-Bt10mqFf.js:71172:54
```

Image

### PR DESCRIPTION
**Pull request by FirelightFlagboy**
- Make client check more robust on `content-type` value
- Add redirection exclusion for server

Fix #11029

### CODE REVIEW

File: client/src/services/resourcesManager.ts [hunk 1]
```diff
@@ -80,7 +80,7 @@ class WebResourcesProvider implements IResourcesProvider {
       throw new Error(`HTTP status ${resp.status} ${resp.statusText}`);
     }
     // Returns index.html if resource does not exist
-    if (resp.headers['content-type'] === 'text/html') {
+    if (resp.headers['content-type'].startsWith('text/html')) {
```
Comment (mmmarcos) [inline client/src/services/resourcesManager.ts:84]:
```suggestion
    // Note content-type header may contain charset (e.g. `text/html; charset=utf-8`)
    if (resp.headers['content-type'].startsWith('text/html')) {
```

File: server/parsec/asgi/__init__.py [hunk 2]
```diff
@@ -49,7 +49,7 @@ class StaticFilesWithSPARedirect(StaticFiles):
     def lookup_path(self, path: str) -> tuple[str, os.stat_result | None]:
         match super().lookup_path(path):
             case (_, None):
-                if path.startswith("assets/"):
+                if path.startswith("assets/") or path.startswith("custom/"):
```
Comment (mmmarcos) [inline server/parsec/asgi/__init__.py:54]:
```suggestion
                # The "assets" and "custom" folders should not be allowed to
                # redirect to index.html
                if path.startswith("assets/") or path.startswith("custom/"):
```

**Review by mmmarcos — APPROVED** [review]
LGTM. Even if is already specified in the commit message, I would add comments to make it explicit when reading code.
