### PR TITLE
[MS] Prevent quit dialog overlaps

### LINKED ISSUE #7131: Quit modal can be opened twice
To reproduce the bug:
- `Cmd + Q` or `Ctrl + F4`
- Click on `Quit` on the tray
- Result -> The animation appears twice.

### PR DESCRIPTION
**Pull request by Ironicbay**
Closes #7131 

## Checklist

Before you submit this pull request, please make sure to:

- [x] Keep changes in the pull request as small as possible
   
- [x] Ensure the commit history is sanitized
   
- [x] Give a meaningful title to your PR
- [x] Describe your changes
   
- [x] Link any related issue in the description
   
- [x] Link any dependent pull request in the description

If this PR is related to GUI:

- [x] I have checked that GUIs affected by my changes are working properly.

### CODE REVIEW

File: client/src/main.ts [hunk 1]
```diff
@@ -154,26 +154,32 @@ async function setupApp(): Promise<void> {
...
-          yesText: 'quit.yes',
-          noText: 'quit.no',
-        });
-      }
-      if (answer === Answer.Yes) {
-        const devices = await getLoggedInDevices();
-        await injectionProvider.cleanAll();
-        for (const device of devices) {
-          await logout(device.handle);
+      if (!isQuitDialogOpen) {
```
Comment (Max-7) [inline client/src/main.ts:165]: Consider leaving the function early in these cases:
```typescript
if (isQuitDialogOpen) {
  return;
}
```
You avoid an extra indentation which also makes the diff way easier to read (and potential conflicts resolution easier to solve).

**Review by Max-7 — CHANGES_REQUESTED** [review]
