### PR TITLE
[MS] Fix incorrect use of translations in the app

### LINKED ISSUE #6786: [MS] When english is selected locale, theme names are in french
image

### PR DESCRIPTION
**Pull request by Ironicbay**
Closes #6786 #6862

### CODE REVIEW

File: client/src/components/core/ms-dropdown/MsDropdown.vue [hunk 1]
```diff
@@ -22,7 +22,7 @@
         slot="end"
         :icon="getIcon()"
       />
-      <span class="input-text">{{ labelRef }}</span>
+      <span class="input-text">{{ $t(labelRef || '') }}</span>
```
Comment (Max-7) [inline client/src/components/core/ms-dropdown/MsDropdown.vue:25]: Empty keys create warnings
`[intlify] Not found '' key in 'fr-FR' locale messages.`

File: client/src/views/devices/GreetDeviceModal.vue [hunk 2]
```diff
@@ -311,9 +311,9 @@ async function updateCanGoForward(): Promise<void> {
 
 function getNextButtonText(): string {
   if (pageStep.value === GreetDeviceStep.WaitForGuest) {
-    return translate('DevicesPage.greet.actions.start');
+    return 'DevicesPage.greet.actions.start';
   } else if (pageStep.value === GreetDeviceStep.Summary) {
-    return translate('DevicesPage.greet.actions.finish');
+    return 'DevicesPage.greet.actions.finish';
   }
   return '';
```
Comment (Max-7) [inline client/src/views/devices/GreetDeviceModal.vue:318]: Same here, careful about empty strings being used as key.

File: client/src/views/header/HeaderPage.vue [hunk 3]
```diff
@@ -267,21 +267,21 @@ onUnmounted(async () => {
...
-      return translate('HeaderPage.titles.about');
+      return 'HeaderPage.titles.about';
     case Routes.ContactDetails:
-      return translate('HeaderPage.titles.myContactDetails');
+      return 'HeaderPage.titles.myContactDetails';
     case Routes.RecoveryExport:
-      return translate('HeaderPage.titles.recoveryExport');
+      return 'HeaderPage.titles.recoveryExport';
     case null:
       return '';
```
Comment (Max-7) [inline client/src/views/header/HeaderPage.vue:286]: Same here.

File: client/src/views/home/CreateOrganizationModal.vue [hunk 4]
```diff
@@ -28,13 +28,13 @@
           v-if="titles.get(pageStep)?.title !== ''"
           class="modal-header__title title-h2"
         >
-          {{ titles.get(pageStep)?.title }}
+          {{ $t(titles.get(pageStep)!.title) }}
```
Comment (Max-7) [inline client/src/views/home/CreateOrganizationModal.vue:31]: Probably will lead to problems if you try to give `undefined` to `$t()`

File: client/src/views/home/CreateOrganizationModal.vue [hunk 5]
```diff
@@ -28,13 +28,13 @@
...
         </ion-title>
         <ion-text
           v-if="titles.get(pageStep)?.subtitle !== ''"
           class="modal-header__text body"
         >
-          {{ titles.get(pageStep)?.subtitle }}
+          {{ $t(titles.get(pageStep)!.subtitle || '') }}
```
Comment (Max-7) [inline client/src/views/home/CreateOrganizationModal.vue:37]: Same thing, no empty strings.

**Review by Max-7 — CHANGES_REQUESTED** [review]

File: client/src/views/files/FoldersPage.vue [hunk 6]
```diff
@@ -95,23 +95,23 @@
...
+                  count: folders.entriesCount() + files.entriesCount(),
+                })
               }}
             </ion-text>
             <ion-text
               class="body item-selected"
               v-if="selectedFilesCount > 0"
             >
-              {{ $t('FoldersPage.itemSelectedCount', { count: selectedFilesCount }, selectedFilesCount) }}
+              {{ $msTranslate({ key: 'FoldersPage.itemSelectedCount', data: { count: selectedFilesCount }, count: selectedFilesCount }) }}
```
Comment (NicoTuxx) [inline client/src/views/files/FoldersPage.vue:109]: why selectedFilesCount is present 2 times?
Is count really useful? Is data not enough?

File: client/src/services/translation.ts [hunk 7]
```diff
@@ -2,12 +2,30 @@
...
 import { DateTime } from 'luxon';
+import { App } from 'vue';
 import { createI18n } from 'vue-i18n';
 
 let i18n: any | null = null;
 
+export interface TranslationData {
+  key: string;
+  data?: object;
+  count?: number;
```
Comment (NicoTuxx) [inline client/src/services/translation.ts:15]: what is `count`? Could it not be passed in data as any other named parameter?

**Review by NicoTuxx — CHANGES_REQUESTED** [review]

File: client/src/services/translation.ts [hunk 8]
```diff
@@ -66,10 +84,14 @@ export function initTranslations(locale?: Locale): any {
   return i18n;
 }
 
-export function translate(key: string, attrs?: object, count?: number): string {
+export function msTranslate(content: Translatable): string {
```
Comment (Max-7) [inline client/src/services/translation.ts:87]: You can let it be named `translate()`, it shouldn't be exported anymore, everything should be done either with `$msTranslate` (most of the time), or if it can't be done in the template, with inject:
```typescript
const msTranslate = inject('msTranslate');

msTranslate('a.b.c');
```

File: client/src/services/translation.ts [hunk 9]
```diff
@@ -2,12 +2,30 @@
...
+}
+
+export type Translatable = string | TranslationData | undefined;
+
+export const TranslationPlugin = {
+  install: (app: App<any>): void => {
+    app.config.globalProperties.$msTranslate = (translatable: Translatable): string => {
+      return msTranslate(translatable);
+    };
+    app.provide('msTranslate', msTranslate);
```
Comment (Max-7) [inline client/src/services/translation.ts:25]: Better to define a key that can be used when injecting later rather than a raw string.

File: client/src/services/translation.ts [hunk 10]
```diff
@@ -2,12 +2,30 @@
...
 
 let i18n: any | null = null;
 
+export interface TranslationData {
+  key: string;
+  data?: object;
+  count?: number;
+}
+
+export type Translatable = string | TranslationData | undefined;
```
Comment (Max-7) [inline client/src/services/translation.ts:18]: `Translatable` shouldn't include `undefined`.

File: client/src/views/about/ChangesModal.vue [hunk 11]
```diff
@@ -38,7 +38,7 @@
                   {{ change.description }}
                 </ion-text>
                 <a
-                  :href="$t('app.projectSources') + '/issues/' + change.issue"
+                  :href="$msTranslate('app.projectSources') + '/issues/' + change.issue"
```
Comment (Max-7) [inline client/src/views/about/ChangesModal.vue:41]: Didn't know this was a thing. This should have it's own key in the translation files,
`$msTranslate('app.projectIssues', { issueId: change.issue });`

Granted, it's not currently used.

File: client/src/views/about/ChangesModal.vue [hunk 12]
```diff
@@ -68,7 +68,7 @@
...
```
Comment (Max-7) [inline client/src/views/about/ChangesModal.vue:71]: Same here, should have its own string.

**Review by NicoTuxx — APPROVED** [review]

File: client/src/common/date.ts [hunk 13]
```diff
@@ -19,17 +19,17 @@ export function formatTimeSince(
   if (!diff || (diff.years && diff.years > 0) || (diff.months && diff.months > 0) || (diff.days && diff.days > 6)) {
     return formatDate(date, format);
   } else if (roundDays) {
-    return translate('common.date.lastLoginDays', { days: diff.days || 0 }, diff.days || 0);
+    return msTranslate({ key: 'common.date.lastLoginDays', data: { days: diff.days || 0 }, count: diff.days || 0 });
```
Comment (Max-7) [inline client/src/common/date.ts:22]: All the functions in `common/` should not call `msTranslate()`, but instead return a `Translatable`.

File: client/src/common/file.ts [hunk 14]
```diff
@@ -78,11 +78,11 @@ function size(bytes: number, system: [number, string][]): string {
 
 export function formatFileSize(bytesize: number): string {
   const SYSTEM: [number, string][] = [
-    [Math.pow(1024, 0), translate('common.filesize.bytes')],
-    [Math.pow(1024, 1), translate('common.filesize.kilobytes')],
-    [Math.pow(1024, 2), translate('common.filesize.megabytes')],
-    [Math.pow(1024, 3), translate('common.filesize.gigabytes')],
-    [Math.pow(1024, 4), translate('common.filesize.terabytes')],
+    [Math.pow(1024, 0), msTranslate('common.filesize.bytes')],
```
Comment (Max-7) [inline client/src/common/file.ts:81]: Should be `const SYSTEM: [number, Translatable][]` instead, we're not translating directly.

File: client/src/common/validators.ts [hunk 15]
```diff
@@ -34,7 +34,7 @@ export const emailValidator: IValidator = async function (value: string) {
   }
   return (await isValidEmail(value))
     ? { validity: Validity.Valid }
-    : { validity: Validity.Invalid, reason: translate('validators.userInfo.email') };
+    : { validity: Validity.Invalid, reason: msTranslate('validators.userInfo.email') };
```
Comment (Max-7) [inline client/src/common/validators.ts:37]: Same here, reason should be a `Translatable`.

**Review by Max-7 — CHANGES_REQUESTED** [review]
The whole idea behind re-doing the translation is that all the texts that are displayed to the user should be `Translatable` and not `string`, and that at no point we should have to use either `msTranslate` or `inject('msTranslate')` and that the translation should only be done at the last moment, in the template.

Everytime a translation is not done in the template, there should be a justification for it.

File: client/src/vite-env.d.ts [hunk 16]
```diff
@@ -8,6 +8,9 @@ declare module '*.vue' {
   // eslint-disable-next-line @typescript-eslint/ban-types
   const component: DefineComponent<{}, {}, any>;
   export default component;
+  interface ComponentCustomProperties {
+    $tr: { tr: (Translatable) => string };
```
Comment (Ironicbay) [inline client/src/vite-env.d.ts:12]: `$tr` or `$msTranslate` ?

**Review by NicoTuxx — APPROVED** [review]
