### PR TITLE
Oxidize trustchain error

### LINKED ISSUE #3171: Oxidize exception `TrustchainError`
# TODOs

- [ ] Oxidize the python exception `TrustchainError` that is already defined in Rust
    > Since that exception is not created in the python code base you don't need to provide a way for python to create it

https://pyo3.rs/latest/function/error_handling.html#foreign-rust-error-types

### PR DESCRIPTION
**Pull request by Volham22**
This close #3171

### CODE REVIEW

File: src/trustchain.rs [hunk 1]
```diff
@@ -122,3 +126,239 @@ impl TrustchainContext {
...
+#[derive(PartialEq)]
+pub(crate) struct TrustchainError(pub(crate) libparsec::core::TrustchainError);
+
+// This object is only here to wrap our `TrustchainError` in a python exception
+// object. Without this object we can't raise or except `TrustchainError` in
+// python code
+create_exception!(_parsec, TrustchainErrorException, PyException);
+
+#[pymethods]
+impl TrustchainError {
```
Comment (FirelightFlagboy) [inline src/trustchain.rs:140]: Do we really need all of those constructor ? For me the exception was not created in the python code.

> Since that exception is not created in the python code base you don't need to provide a way for python to create it

File: src/trustchain.rs [hunk 2]
```diff
@@ -122,3 +126,239 @@ impl TrustchainContext {
...
+            Err(PyAttributeError::new_err("No such attribute `got`"))
+        }
+    }
+}
+
+gen_proto!(TrustchainError, __richcmp__, eq);
+gen_proto!(TrustchainError, __str__); // Needed for python's exceptions
+gen_proto!(TrustchainError, __repr__);
+
+impl From<TrustchainError> for PyErr {
```
Comment (FirelightFlagboy) [inline src/trustchain.rs:332]: Don't we want to use `TrustchainErrorException` here ?

**Review by FirelightFlagboy — CHANGES_REQUESTED** [review]
I don't see the exception `TrustchainError` being deleted in the python code, I'm missing something ?

File: src/trustchain.rs (hunk 2 above)
Comment (Volham22) [reply src/trustchain.rs:332]: This impl isn't used at all. We should just remove it

**Comment by Volham22** [comment]
> I don't see the exception `TrustchainError` being deleted in the python code, I'm missing something ?

Done.

File: src/trustchain.rs [hunk 3]
```diff
@@ -122,3 +126,129 @@ impl TrustchainContext {
         ))
     }
 }
+
+#[pyclass]
+#[derive(PartialEq)]
```
Comment (TimeEngineer) [inline src/trustchain.rs:131]: Remove `PartialEq`

File: src/binding_utils.rs [hunk 4]
```diff
@@ -135,6 +136,11 @@ pub fn rs_to_py_regex<'py>(py: Python<'py>, regex: &Regex) -> PyResult<&'py PyAn
     re.call_method1("compile", args)
 }
 
+pub fn to_trustchain_error_exception(err: libparsec::core::TrustchainError) -> PyErr {
+    let python_error = TrustchainError(err);
+    TrustchainErrorException::new_err(python_error)
+}
```
Comment (FirelightFlagboy) [inline src/binding_utils.rs:142]: Using this code block into the trait `impl From<libparsec::core::TrustchainError> for PyErr` would simplify the error handling part

as we don't need to use `.map_err(to_trustchain_error_exception)` before unwrapping with `?` when we use rust code the return `libparsec::core::TrustchainError`

File: src/trustchain.rs [hunk 5]
```diff
@@ -122,3 +126,129 @@ impl TrustchainContext {
...
+
+// This object is only here to wrap our `TrustchainError` in a python exception
+// object. Without this object we can't raise or except `TrustchainError` in
+// python code
+create_exception!(_parsec, TrustchainErrorException, PyException);
+
+#[pymethods]
+impl TrustchainError {
+    #[getter]
+    fn path(&self) -> PyResult<String> {
```
Comment (TimeEngineer) [inline src/trustchain.rs:142]: Can it be a `&str` instead of `String` ?

**Review by FirelightFlagboy — COMMENTED** [review]
One more thing

File: src/trustchain.rs [hunk 6]
```diff
@@ -122,3 +126,129 @@ impl TrustchainContext {
...
+        } else {
+            Err(PyAttributeError::new_err("No such attribute `exc`"))
+        }
+    }
+
+    #[getter]
+    fn user_id(&self) -> PyResult<UserID> {
+        match &self.0 {
+            libparsec::core::TrustchainError::InvalidSelfSignedUserCertificate { user_id } => {
+                Ok(ids::UserID(user_id.clone()))
```
Comment (TimeEngineer) [inline src/trustchain.rs:177]: Why do you keep `ids::` ?

File: src/trustchain.rs [hunk 7]
```diff
@@ -1,16 +1,20 @@
 // Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 (eventually AGPL-3.0) 2016-present Scille SAS
 
-use pyo3::{import_exception, prelude::*, types::PyTuple};
-
 use crate::{
     api_crypto::VerifyKey,
+    binding_utils::{gen_proto, to_trustchain_error_exception},
     certif::{DeviceCertificate, RevokedUserCertificate, UserCertificate},
-    ids::{DeviceID, UserID},
+    ids::{self, DeviceID, UserID},
```
Comment (TimeEngineer) [inline src/trustchain.rs:7]: You can remove `self` then

File: src/binding_utils.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (FirelightFlagboy) [reply src/binding_utils.rs:142]: see https://github.com/Scille/parsec-cloud/pull/3209#discussion_r988014366

Comment (Volham22) [reply src/binding_utils.rs:142]: I agree but shouldn't we avoid to put python related code in `libparsec::core` ? We can't implement `From<libparsec::core::TrustchainError>` in `src/trustchain.rs`

Comment (TimeEngineer) [reply src/binding_utils.rs:142]: Maybe add a file `error.rs` in `src/` ?

Comment (Volham22) [reply src/binding_utils.rs:142]: It will not work we would get an error like this `only traits defined in the current crate can be implemented for types defined outside of the crate` by the compiler

Comment (Volham22) [reply src/binding_utils.rs]: I've implemented `From<TrustchainError>` trait for `PyErr` this way we can just do a `.map_err(TrustchainError)?`

Comment (FirelightFlagboy) [reply src/binding_utils.rs]: I was thinking of something like that 

```rust
impl From<libparsec::TrustchainError> for TrustchainError {}
impl From<TrustchainError> for PyErr {}
```

File: src/trustchain.rs [hunk 8]
```diff
@@ -122,3 +126,126 @@ impl TrustchainContext {
...
+    }
+
+    #[getter]
+    fn verified_timestamp(&self) -> PyResult<DateTime> {
+        if let libparsec::core::TrustchainError::SignaturePosteriorUserRevocation {
+            verified_timestamp,
+            ..
+        } = &self.0
+        {
+            Ok(time::DateTime(*verified_timestamp))
```
Comment (TimeEngineer) [inline src/trustchain.rs:201]: You can do the same for `time`

File: src/trustchain.rs [hunk 9]
```diff
@@ -122,3 +126,126 @@ impl TrustchainContext {
...
+            ))
+        }
+    }
+
+    #[getter]
+    fn user_timestamp(&self) -> PyResult<DateTime> {
+        if let libparsec::core::TrustchainError::SignaturePosteriorUserRevocation {
+            user_timestamp,
+            ..
+        } = &self.0
```
Comment (TimeEngineer) [inline src/trustchain.rs:214]: Remove borrow and remove deference

File: src/binding_utils.rs (hunk 4 above)
Comment (Volham22) [reply src/binding_utils.rs]: Does it matter since we'll need to do at least a `map_err` to be able to use `?`?

**Review by FirelightFlagboy — APPROVED** [review]

**Review by FirelightFlagboy — APPROVED** [review]

**Review by TimeEngineer — APPROVED** [review]
