### PR TITLE
Fix Macos Fuse mountpoint initialization

### LINKED ISSUE #8735: Fail during initialization of macos mountpoint
Sentry Issue: [PARSEC3-LIBPARSEC-E](https://scille.sentry.io/issues/5990865999/?referrer=github_integration)

```
panic: Capability available: 16
  ?, in _rust_begin_unwind
  ?, in libparsec_platform_mountpoint::unix::filesystem::Filesystem::init
  ?, in fuser::request::Request::dispatch
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by FirelightFlagboy**
Closes #8735

### CODE REVIEW

File: libparsec/crates/platform_mountpoint/src/unix/filesystem.rs [hunk 1]
```diff
@@ -208,6 +208,20 @@ pub(crate) static LOOKUP_HOOK: Mutex<
     Option<Box<dyn FnMut(&FsPath) -> Option<Result<EntryStat, WorkspaceStatEntryError>> + Send>>,
 > = Mutex::new(None);
 
+macro_rules! add_capabilities {
```
Comment (mmmarcos) [inline libparsec/crates/platform_mountpoint/src/unix/filesystem.rs:211]: I'd add a comment
```suggestion
/// Helper macro to add one or many capabilities to fuser config.
macro_rules! add_capabilities {
```
Or maybe even with an example?
```suggestion
/// Helper macro to add one (or multiple) capabilities to fuser config.
///
/// Example:
/// ```
/// add_capabilities!(config, <capability>)
/// add_capabilities!(config, <capability1>, ..., <capabilityN>)
/// ```
macro_rules! add_capabilities {
```

**Review by mmmarcos — APPROVED** [review]
