### PR TITLE
[MS] Fix visible searchbar issue

### LINKED ISSUE #5681: [🐛 Bug] Searchbar should be always visible

### PR DESCRIPTION
**Pull request by fabienSvtr**
## Describe your changes

The bug is handled globally, but the scrolling content must be handled independently.
image

## Checklist

Before you submit this pull request, please make sure to:

- [ ] Keep changes in the pull request as small as possible
   
- [ ] Ensure the commit history is sanitized
   
- [ ] Give a meaningful title to your PR
- [ ] Describe your changes
   
- [ ] Link any related issue in the description
   
- [ ] Link any dependent pull request in the description

closes #5681

### CODE REVIEW

File: client/src/parsec/workspace.ts [hunk 1]
```diff
@@ -202,6 +202,87 @@ export async function getWorkspaceSharing(
         },
         WorkspaceRole.Contributor,
       ],
+      [
```
Comment (Max-7) [inline client/src/parsec/workspace.ts:205]: Remove.

**Review by Max-7 — CHANGES_REQUESTED** [review]
Screenshot 2024-01-03 145347

Can you check the `UserDetailsModal` too? It doesn't scroll.

**Review by Max-7 — APPROVED** [review]
