### PR TITLE
[MS] Use progress bars from lib in FileOperationMenu

### LINKED ISSUE #8468: [🐛 | Bug]: `FileOperationMenu` has a huge impact on CPU usage
### Parsec version tested on:

3.0.0-rc8

### Platforms tested on:

MacOS

### Bug description:

On my computer:
- Parsec renderer takes approximately 2% of my CPU at idle in a workspace on `FoldersPage`
- With 1 item in `FileOperationMenu` this jumps to 6%
- With the current 'fix' limiting to 10 items, CPU usage is at ~12%
- Up to 80% with ~100 items

### Relevant output:

_No response_

### PR DESCRIPTION
**Pull request by Ironicbay**
Closes #8468

### CODE REVIEW

**Comment by Ironicbay** [comment]
Current appearance:

https://github.com/user-attachments/assets/9de44e26-0a65-4df1-bbb2-a4b5075fba91

**Review by NicoTuxx — APPROVED** [review]

**Comment by NicoTuxx** [comment]
image

File: client/src/views/files/FileOperationMenu.vue [hunk 1]
```diff
@@ -154,8 +154,8 @@ const menu = useUploadMenu();
 const fileOperationManager: FileOperationManager = inject(FileOperationManagerKey)!;
 const errorHappenedInUpload: Ref<boolean> = ref(false);
 const inProgressItems: Ref<Array<OperationItem>> = ref([]);
-const doneItems = ref(new FIFO<OperationItem>(10));
-const errorItems = ref(new FIFO<OperationItem>(10));
+const doneItems = ref(new FIFO<OperationItem>(100));
```
Comment (Max-7) [inline client/src/views/files/FileOperationMenu.vue:157]: Might as well keep it at 10 for now, it's going to be replaced later anyway.

**Review by Max-7 — APPROVED** [review]
