### PR TITLE
[MS] Added some try/catch on electron side

### LINKED ISSUE #8531: Error: Command failed: chcp 65001 >NUL & powershell.exe -NoProfile -NonInteractive -InputFormat None -Co...
Sentry Issue: [PARSEC3-FRONTEND-1E](https://scille.sentry.io/issues/5820552309/?referrer=github_integration)

```
Error: Command failed: chcp 65001 >NUL & powershell.exe -NoProfile -NonInteractive -InputFormat None -Command "Get-AuthenticodeSignature -LiteralPath 'C:\Users\Kelly\AppData\Local\parsec-updater\pending\temp-Parsec_3.0.1_win_x86_64.exe' | ConvertTo-Json -Co...
  File "node:internal/errors", line 984, in genericNodeError
  File "node:internal/errors", line 538, in wrappedFn
  File "node:child_process", line 422, in ChildProcess.exithandler
  File "node:events", line 519, in ChildProcess.emit
  File "node:internal/child_process", line 1105, in maybeClose
...
(1 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by Max-7**
Closes #8531 

- [X] Keep changes in the pull request as small as possible
- [X] Ensure the commit history is sanitized
- [X] Give a meaningful title to your PR
- [X] Describe your changes
- [X] Link any related issue in the description

### CODE REVIEW

File: client/electron/src/updater.ts [hunk 1]
```diff
@@ -448,27 +448,38 @@ export default class AppUpdater {
...
+      console.error('Could not check for updates', error);
+      return;
     }
   }
 
-  quitAndInstall(): void {
-    if (!this.isUpdateDownloaded()) {
-      console.log('quitAndInstall() called when update has not been downloaded.');
-      return;
+  quitAndInstall(): boolean {
```
Comment (Ironicbay) [inline client/electron/src/updater.ts:471]: Why change the return type?

**Review by Ironicbay — APPROVED** [review]

File: client/electron/src/updater.ts (hunk 1 above)
Comment (Max-7) [reply client/electron/src/updater.ts:471]: `quitAndInstall` can be called following a user action. My initial thought was to be able to warn the user in case it fails, because right now, you could get a situation where the user clicks the button to update and nothing happens. It is quite hard to implement though, so I gave up (for now). At least until we're sure that those try/catch really do something.
I think it can stay as a boolean for later.
