### PR TITLE
[MS] Reduce 'done' items to 10 in import menu and rename it to 'last …

### LINKED ISSUE #8393: [🐛 | Bug]: GUI breaks when `FileOperationMenu` tab with many items is open
### Parsec version tested on:

3.0.0-rc7

### Platforms tested on:

MacOS

### Bug description:

GUI becomes very laggy and navigating through the folder tree bugs out (fails to find paths, incorrect breadcrumbs)

To replicate:
- Import many files, in my case a folder with a few hundred files and some subfolders, which I import twice or thrice to build a layered folder tree
- Leave the `FileOperationMenu` open on the `Done` tab (which displays the few hundred elements imported)
- Enjoy

### Relevant output:

_No response_

### PR DESCRIPTION
**Pull request by Ironicbay**
Closes #8393

### CODE REVIEW

File: client/src/views/files/FileOperationMenu.vue [hunk 1]
```diff
@@ -232,24 +197,34 @@ function getFileOperationComponent(item: OperationItem): Component | undefined {
 }
 
 function updateImportState(id: string, state: FileOperationState, stateData?: StateData): void {
-  const operation = fileOperations.value.find((op) => op.data.id === id);
+  const operation = inProgressItems.value.find((op) => op.data.id === id);
```
Comment (Max-7) [inline client/src/views/files/FileOperationMenu.vue:200]: You could use `findIndex` right here and use it to get the matching operation, just to avoid going through the list againt when removing the item.

**Review by Max-7 — CHANGES_REQUESTED** [review]

**Review by Max-7 — APPROVED** [review]

**Review by Max-7 — APPROVED** [review]
