### PR TITLE
[MS] Updated how external links are opened + fixed changelog link

### LINKED ISSUE #8378: [🐛 | Bug]: Missing `v` prefix to documentation link
### Parsec version tested on:

3.0.0-rc.7

### Platforms tested on:

Linux

### Bug description:

On the device list page (home), the documentation link use an invalid link <https://docs.parsec.cloud/en/3.0.0-rc.7/> where is should be <https://docs.parsec.cloud/en/v3.0.0-rc.7/>

> Note the added `v` before `3.0.0`

### Relevant output:

_No response_

### PR DESCRIPTION
**Pull request by Max-7**
Closes #8378 

- [X] Keep changes in the pull request as small as possible
- [X] Ensure the commit history is sanitized
- [X] Give a meaningful title to your PR
- [X] Describe your changes
- [X] Link any related issue in the description

### CODE REVIEW

File: client/src/services/environment.ts [hunk 1]
```diff
@@ -60,10 +60,45 @@ function getTrialServers(): Array<string> {
   return DEFAULT_TRIAL_SERVERS;
 }
 
+const CLEAN_APP_VERSION = `${APP_VERSION.replace('+dev', '')}`;
```
Comment (FirelightFlagboy) [inline client/src/services/environment.ts:63]: Note: For nightly build, `+{local}` is set to a short commit id (it replace `dev`).

I'm think If it would be simple to handle that part with `misc/version_updater.py` :thinking:, we already have a function (`hide_patch_version`) that can remove the patch version of python, we could have something similar for `CLEAN_APP_VERSION`

**Review by Ironicbay — APPROVED** [review]

File: client/src/services/environment.ts (hunk 1 above)
Comment (Max-7) [reply client/src/services/environment.ts]: I update the cleaning part slightly to remove anything after the `+` (if present). Probably good enough.
