### PR TITLE
Move save functions to platform filesystem

### LINKED ISSUE #12003: Saving content
<details>

<summary>Diff between web&native</summary>

Native:

- `save_content`: https://github.com/Scille/parsec-cloud/blob/1c8e6cc753058f403ac632d4610d9d6a0839f43f/libparsec/crates/platform_device_loader/src/native/mod.rs#L268-L304
- error:
  - StorageNotAvailable,
  - InvalidPath
  - RemoteOpaqueKeyUploadOffline (Should not depends on network for save operation)
  - RemoteOpaqueKeyUploadFailed (Should not depends on network for save operation)
  - Internal

Web:

- `save_raw_content`: https://github.com/Scille/parsec-cloud/blob/1c8e6cc753058f403ac632d4610d9d6a0839f43f/libparsec/crates/platform_device_loader/src/web/internal.rs#L257-L279
- error: (`SaveRawDataError`)
  - GetFileHandleError
    - CastError
    - AwaitPromiseError
    - DomExceptionError
    - NotFoundError
    - NotAFile
  - WriteAllError
    - *CastError
    - *NotFoundError
    - *DomExceptionError
    - CreateWriteable
    - CannotEdit
    - NoSpaceLeft
    - Write
    - Close

</details>

Normalized Error:

- StorageNotAvailable (storage API not available)
- NotAFile (the path point to something else than a file)
- InvalidParent (the parent folder is not a folder)
- InvalidPath (Malformated path e.g: missing filename)
- ParentNotFound (did not found the parent folder) (likely not used but TOCTOU :shrug:)
- CannotEdit (cannot write/edit file)
- NoSpaceLeft (not enough space to write content)
- Internal (other errors, mostly platform specific)
- Impl `From<std::io::Error>`

Normalized `save_content`:

```rust
pub async fn save_content(path: &std::path::Path, content: &[u8]) -> Result<(), SaveContentError> {
  todo!()
}

```

### PR DESCRIPTION
**Pull request by AureliaDolo**
Fix #12003

### CODE REVIEW

File: libparsec/crates/platform_device_loader/src/web/internal.rs [hunk 1]
```diff
@@ -245,36 +246,11 @@ impl Storage {
     }
 
     pub(crate) async fn save_device_file(
-        &self,
```
Comment (AureliaDolo) [inline libparsec/crates/platform_device_loader/src/web/internal.rs:247]: Maybe move that somewhere else, but where ?

File: libparsec/crates/platform_filesystem/src/lib.rs [hunk 2]
```diff
@@ -5,6 +5,35 @@ mod native;
 #[cfg(target_arch = "wasm32")]
 mod web;
 
+#[derive(Debug, thiserror::Error)]
+pub enum SaveContentError {
+    #[error("")]
```
Comment (AureliaDolo) [inline libparsec/crates/platform_filesystem/src/lib.rs]: Todo

File: libparsec/crates/platform_device_loader/src/web/internal.rs (hunk 1 above)
Comment (FirelightFlagboy) [reply libparsec/crates/platform_device_loader/src/web/internal.rs:247]: As the migration progress, I expect that we remove more and more methods/functions in `internal.rs` until it's empty at the end.

File: libparsec/crates/platform_filesystem/src/lib.rs [hunk 3]
```diff
@@ -5,6 +5,35 @@ mod native;
...
+
+pub async fn save_content(path: &std::path::Path, content: &[u8]) -> Result<(), SaveContentError> {
+    #[cfg(not(target_arch = "wasm32"))]
+    return native::save_content(path, content).await;
+    #[cfg(target_arch = "wasm32")]
+    {
+        let store = web::common::internal::Storage::new().await?;
+        return web::save_content(store, path, content).await;
+    }
+}
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_filesystem/src/lib.rs]: **suggestion:** What do you think about declaring 2 `save_content`?

Both would have different body specific to the targeted platform

File: libparsec/crates/platform_filesystem/src/native/save.rs [hunk 4]
```diff
@@ -1 +1,37 @@
 // Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS
+
+use crate::SaveContentError;
+
+pub async fn save_content(path: &std::path::Path, content: &[u8]) -> Result<(), SaveContentError> {
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_filesystem/src/native/save.rs:5]: **issue:** Not using the correct error variants

File: libparsec/crates/platform_filesystem/src/web/common/internal.rs [hunk 5]
```diff
@@ -0,0 +1,18 @@
+// Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 2016-present Scille SAS
+
+use super::error::NewStorageError;
+use super::wrapper::Directory;
+pub struct Storage {
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_filesystem/src/web/common/internal.rs]: **chore:** 
```suggestion
use super::wrapper::Directory;

pub struct Storage {
```

File: libparsec/crates/platform_device_loader/src/web/error.rs [hunk 6]
```diff
@@ -250,3 +251,21 @@ impl From<SaveRawDataError> for crate::SavePkiLocalPendingError {
...
+            | SaveContentError::InvalidParent
+            | SaveContentError::ParentNotFound
+            | SaveContentError::NoSpaceLeft
+            | SaveContentError::NotAFile
+            | SaveContentError::CannotEdit
+            | SaveContentError::InvalidPath
+            | SaveContentError::Internal(_) => SaveDeviceError::Internal(value.into()),
+            // TODO do something with save device error
+            // SaveContentError::NotAFile => SaveDeviceError::NotAFile,
+            // SaveContentError::CannotEdit => SaveDeviceError::CannotEdit,
```
Comment (AureliaDolo) [inline libparsec/crates/platform_device_loader/src/web/error.rs]: Add these variants to save device error ?

File: libparsec/crates/platform_device_loader/tests/units/async_enrollment.rs [hunk 7]
```diff
@@ -73,18 +74,29 @@ async fn save_list_load(tmp_path: TmpPath) {
...
-            &PrivateKey::generate(),
-            &SecretKey::generate(),
-            tmp_path.clone(), // The target file is already a folder !
-        )
-        .await,
-        Err(SaveAsyncEnrollmentLocalPendingError::InvalidPath(_))
+        output,
+        Err(SaveAsyncEnrollmentLocalPendingError::SaveContentError(
+            SaveContentError::NotAFile
+        ))
```
Comment (AureliaDolo) [inline libparsec/crates/platform_device_loader/tests/units/async_enrollment.rs]: 💀

File: libparsec/crates/account/src/register_new_device.rs [hunk 8]
```diff
@@ -148,12 +148,10 @@ pub(super) async fn account_register_new_device(
         save_device(&account.config_dir, &save_strategy, &new_device, key_file)
             .await
             .map_err(|err| match err {
-                SaveDeviceError::StorageNotAvailable => {
-                    AccountRegisterNewDeviceError::StorageNotAvailable
-                }
-                SaveDeviceError::InvalidPath(error) => {
-                    AccountRegisterNewDeviceError::InvalidPath(error)
+                SaveDeviceError::SaveContentError(e) => {
+                    AccountRegisterNewDeviceError::Internal(e.into()) // TODO #11955
```
Comment (FirelightFlagboy) [inline libparsec/crates/account/src/register_new_device.rs]: **question:** Sure about the issue listed in TODO? 

#11955 was closed as not planned because would have been treated by the sub-tasks of #11954 to remove dependency of `error_set` (I've re-openend it since).

Furthermore, the issue is lacking a listing of places where additional error variant should be handled.

File: libparsec/crates/platform_device_loader/src/web/wrapper.rs [hunk 9]
```diff
@@ -111,6 +111,7 @@ impl Directory {
         }
     }
 
+    #[allow(unused)]
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_device_loader/src/web/wrapper.rs]: **nitpick:** 
```suggestion
    #[expect(unused)]
```

File: libparsec/crates/account/src/register_new_device.rs (hunk 8 above)
Comment (AureliaDolo) [reply libparsec/crates/account/src/register_new_device.rs]: I linked that issue because from my understanding #11954 was more about what's happening inside platform device loader and the idea here is to do a more general clean up. (it could be a new issue) Here it's a reminder to clean up the errors that are not part of platform device loader but that are derived from some platform device loader errors.

File: libparsec/crates/platform_device_loader/src/web/wrapper.rs (hunk 9 above)
Comment (AureliaDolo) [reply libparsec/crates/platform_device_loader/src/web/wrapper.rs]: It is used in  `wasm-pack test --headless --firefox libparsec/crates/platform_device_loader`

Comment (FirelightFlagboy) [reply libparsec/crates/platform_device_loader/src/web/wrapper.rs]: Use `cfg_attr` then

File: libparsec/crates/account/src/register_new_device.rs [hunk 10]
```diff
@@ -148,19 +148,19 @@ pub(super) async fn account_register_new_device(
...
                 }
                 SaveDeviceError::RemoteOpaqueKeyUploadFailed { server, error } => {
                     AccountRegisterNewDeviceError::RemoteOpaqueKeyUploadFailed { server, error }
                 }
+                SaveDeviceError::StorageNotAvailable => {
+                    AccountRegisterNewDeviceError::StorageNotAvailable
+                }
+                SaveDeviceError::InvalidPath => {
+                    AccountRegisterNewDeviceError::InvalidPath(anyhow::anyhow!("invalid path"))
+                }
```
Comment (AureliaDolo) [inline libparsec/crates/account/src/register_new_device.rs]: Therehas been a few round trips, I'll move that kind of stuff back to clear the diff

File: libparsec/crates/account/src/register_new_device.rs
Comment (FirelightFlagboy) [inline libparsec/crates/account/src/register_new_device.rs:1]: **nitpick:** Diff can be simplified if line are reordered before the change

File: libparsec/crates/client/src/client/recovery_device.rs
Comment (FirelightFlagboy) [inline libparsec/crates/client/src/client/recovery_device.rs:1]: **nitpick:** Diff can be simplified if line are reordered before the change

File: libparsec/crates/client/src/invite/async_enrollment/submit.rs [hunk 11]
```diff
@@ -143,15 +143,15 @@ pub async fn submit_async_enrollment(
     )
     .await
     .map_err(|err| match err {
-        SaveAsyncEnrollmentLocalPendingError::StorageNotAvailable => {
+        SaveAsyncEnrollmentLocalPendingError::NoSpaceLeft => {
             SubmitAsyncEnrollmentError::StorageNotAvailable
```
Comment (FirelightFlagboy) [inline libparsec/crates/client/src/invite/async_enrollment/submit.rs:147]: **issue:** Either it's missing a TODO comment with a issue reference or we are returning the wrong error variant for `no space left`

File: libparsec/crates/client/src/invite/async_enrollment/submitter_finalize.rs
Comment (FirelightFlagboy) [inline libparsec/crates/client/src/invite/async_enrollment/submitter_finalize.rs:1]: **nitpick:** Diff can be simplified if line are reordered before the change

File: libparsec/crates/platform_device_loader/src/lib.rs [hunk 12]
```diff
@@ -317,10 +318,10 @@ pub async fn load_device(
 
 #[derive(Debug, thiserror::Error)]
 pub enum SaveDeviceError {
-    #[error("Device storage is not available")]
+    #[error("No space left")]
     StorageNotAvailable,
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_device_loader/src/lib.rs]: **issue:** We should rename the variant, this would be confusing to have StorageNotAvail for NoSpaceLeft

File: libparsec/crates/client/src/invite/async_enrollment/submit.rs (hunk 11 above)
Comment (AureliaDolo) [reply libparsec/crates/client/src/invite/async_enrollment/submit.rs:147]: see #12081

File: libparsec/crates/platform_device_loader/src/lib.rs (hunk 12 above)
Comment (AureliaDolo) [reply libparsec/crates/platform_device_loader/src/lib.rs]: see https://github.com/Scille/parsec-cloud/issues/12081

File: libparsec/crates/platform_device_loader/src/lib.rs [hunk 13]
```diff
@@ -344,6 +345,23 @@ pub enum SaveDeviceError {
...
+        match value {
+            SaveContentError::NotAFile
+            | SaveContentError::InvalidParent
+            | SaveContentError::InvalidPath
+            | SaveContentError::ParentNotFound
+            | SaveContentError::CannotEdit => SaveDeviceError::InvalidPath,
+
+            SaveContentError::NoSpaceLeft | SaveContentError::StorageNotAvailable => {
+                SaveDeviceError::StorageNotAvailable
+            }
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_device_loader/src/lib.rs]: **issue:** In the web context, `NoSpaceLeft` and `StorageNotAvailable` is not the same things.

That would cause the GUI to display invalid message when handling the error variant if we consider that `StorageNotAvailable == NoSpaceLeft` (as the error message rewrite above)

Comment (AureliaDolo) [reply libparsec/crates/platform_device_loader/src/lib.rs]: Indeed, should NoSpaceLeft be kept as internal then ?

File: libparsec/crates/platform_device_loader/src/lib.rs [hunk 14]
```diff
@@ -317,10 +318,10 @@ pub async fn load_device(
 
 #[derive(Debug, thiserror::Error)]
 pub enum SaveDeviceError {
-    #[error("Device storage is not available")]
+    #[error("No space left")]
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_device_loader/src/lib.rs]: **nitpick:** Should also revert the error message as it will be done in #12081
