### PR TITLE
Fix CLI recovery device feature

### LINKED ISSUE #8747: Fix recovery device in CLI
`parsec-cli` appear to use the recovery device mechanism the intended way.

Currently way creating a recovery device, it use the current device without creating a new device.
And when importing the recovery device, we import the device as is without using it to create a new device.

The shamir (wip) system behave like intended and we could reuse some part to fix the issues:

- When creating a shamir device: 
  
  https://github.com/Scille/parsec-cloud/blob/96eb831587aa68f860ea7452b4b423876c1679c0/libparsec/crates/client/src/certif/shamir_recovery_setup.rs#L241-L258

- When importing a shamir device: 

  https://github.com/Scille/parsec-cloud/blob/96eb831587aa68f860ea7452b4b423876c1679c0/libparsec/crates/client/src/certif/shamir_recovery_setup.rs#L310-L318

## TODOs

- [ ] [CLI] Create a dedicated device when creating a recovery device
- [ ] [CLI] Create a dedicated device when importing a recovery device

### PR DESCRIPTION
**Pull request by AureliaDolo**
Closes #8747

Depends on #8585

### CODE REVIEW

File: cli/src/commands/device/import_recovery_device.rs [hunk 1]
```diff
@@ -12,6 +12,9 @@ crate::clap_parser_with_shared_opts_builder!(
         /// Recovery file
         #[arg(short, long)]
         input: PathBuf,
+         /// new device label
+         #[arg(short, long)]
+         label: String,
```
Comment (FirelightFlagboy) [inline cli/src/commands/device/import_recovery_device.rs:17]: Indentation

File: cli/src/commands/device/export_recovery_device.rs [hunk 2]
```diff
@@ -29,15 +29,19 @@ pub async fn main(args: Args) -> anyhow::Result<()> {
...
+        .export_recovery_device(DeviceLabel::try_from(format!("recovery-{now}").as_str())?)
+        .await?;
+
+    std::fs::write(&output, data)?;
 
     handle.stop_with_message(format!(
-        "Saved in {}\n{RED}Save the recovery passphrase in a safe place:{RESET} {GREEN}{}{RESET}",
+        "Recovery data saved in {}\n{RED}Save the recovery passphrase in a safe place:{RESET} {GREEN}{}{RESET}",
         output.display(),
         passphrase.as_str()
```
Comment (FirelightFlagboy) [inline cli/src/commands/device/export_recovery_device.rs:46]:
```suggestion
        "Recovery device saved at {path}\n{RED}Save the recovery passphrase in a safe place:{RESET} {GREEN}{passwd}{RESET}",
        path = output.display(),
        passwd = passphrase.as_str()
```

File: cli/src/commands/device/export_recovery_device.rs [hunk 3]
```diff
@@ -29,15 +29,19 @@ pub async fn main(args: Args) -> anyhow::Result<()> {
...
-    // The recovery device must be generated first
-    let passphrase = save_recovery_device(&output, &device).await?;
+    let client = load_client(&config_dir, device.clone(), password_stdin).await?;
+
+    let now = DateTime::now();
+    let (passphrase, data) = client
+        .export_recovery_device(DeviceLabel::try_from(format!("recovery-{now}").as_str())?)
+        .await?;
+
+    std::fs::write(&output, data)?;
```
Comment (FirelightFlagboy) [inline cli/src/commands/device/export_recovery_device.rs:41]:
```suggestion
    tokio::fs::write(&output, data).await?;
```

File: cli/src/commands/device/import_recovery_device.rs [hunk 4]
```diff
@@ -20,28 +23,22 @@ pub async fn main(args: Args) -> anyhow::Result<()> {
...
         config_dir,
         password_stdin,
+        label,
     } = args;
     log::trace!(
         "Importing recovery device from {} (confdir={})",
         input.display(),
         config_dir.display(),
     );
+    let recovery_device = std::fs::read(input)?;
```
Comment (FirelightFlagboy) [inline cli/src/commands/device/import_recovery_device.rs:33]:
```suggestion
    let recovery_device = tokio::fs::read(input).await?;
```

File: cli/tests/integration/device/import_recovery_device.rs [hunk 5]
```diff
@@ -12,16 +13,22 @@ async fn import_recovery_device(tmp_path: TmpPath) {
...
     let input = tmp_path.join("recovery_device");
 
-    let passphrase = libparsec::save_recovery_device(&input, &alice)
+    let client = start_client(alice).await.unwrap();
+
+    let (passphrase, data) = client
+        .export_recovery_device(DeviceLabel::try_from("recovery".to_string().as_str()).unwrap())
         .await
         .unwrap();
+    std::fs::write(&input, data).unwrap();
```
Comment (FirelightFlagboy) [inline cli/tests/integration/device/import_recovery_device.rs:22]:
```suggestion
    tokio::fs::write(&input, data).await.unwrap();
```

File: cli/src/commands/device/export_recovery_device.rs [hunk 6]
```diff
@@ -29,17 +29,21 @@ pub async fn main(args: Args) -> anyhow::Result<()> {
...
     let mut handle = start_spinner("Saving recovery device file".into());
 
-    // TODO: save recovery device instead of local device
-    // The recovery device must be generated first
-    let passphrase = save_recovery_device(&output, &device).await?;
+    let client = load_client(&config_dir, device.clone(), password_stdin).await?;
+
+    let now = DateTime::now();
+    let (passphrase, data) = client
+        .client_export_recovery_device(DeviceLabel::try_from(format!("recovery-{now}").as_str())?)
```
Comment (FirelightFlagboy) [inline cli/src/commands/device/export_recovery_device.rs:38]: **nitpick**: Could we remove the prefix `client_` for the used method ?

File: cli/src/commands/device/export_recovery_device.rs [hunk 7]
```diff
@@ -2,14 +2,14 @@
...
+use libparsec::{DateTime, DeviceLabel};
 
 use crate::utils::*;
 
 crate::clap_parser_with_shared_opts_builder!(
     #[with = config_dir, device, password_stdin]
     pub struct Args {
-        /// Recovery device output
+        /// Path where to save recovery device data
         #[arg(short, long)]
```
Comment (FirelightFlagboy) [inline cli/src/commands/device/export_recovery_device.rs:13]:
```suggestion
        #[arg]
```

I would say to directly pass the output path as an arg over an option

File: cli/tests/integration/device/import_recovery_device.rs (hunk 5 above)
Comment (FirelightFlagboy) [reply cli/tests/integration/device/import_recovery_device.rs:24]: Still present

**Review by FirelightFlagboy — APPROVED** [review]

**Review by FirelightFlagboy — APPROVED** [review]
