### PR TITLE
[MS] fix HomePage transitions

### LINKED ISSUE #6003: Re-enable animation in homepage between devices list and login
Turned of in #5983

### PR DESCRIPTION
**Pull request by NicoTuxx**
closes #6003

### CODE REVIEW

**Review by fabienSvtr — APPROVED** [review]

File: client/src/transitions/SlideHorizontal.vue [hunk 1]
```diff
@@ -1,38 +1,54 @@
...
   </transition>
 </template>
 
 <script setup lang="ts">
+import { Position } from '@/transitions/types';
 import { defineProps } from 'vue';
 
 const props = defineProps<{
-  reverseDirection?: boolean;
+  from: Position;
```
Comment (Max-7) [inline client/src/transitions/SlideHorizontal.vue:13]: I'm not a big fan of having two props to define the transition behavior, because it delegates the configuration to the caller.

Which means you get a lot of logic in the caller:
```html
<slide-horizontal
  :from="state === HomePageState.OrganizationList ? Position.Left : Position.Right"
  :to="state === HomePageState.OrganizationList ? Position.Right : Position.Left"
>
```
and it can lead to weird things:
```html
<slide-horizontal
  :from="Position.Left"
  :to="Position.Left"
>
```
Why not define instead a `TransitionDirection` as `LeftToRight` and `RightToLeft`? It reduces the amount of logic, it's easier to understand, and it's less prone to errors. It does require a bit more logic in the component itself but that's ok.

**Review by Max-7 — CHANGES_REQUESTED** [review]

**Review by Max-7 — APPROVED** [review]
