### PR TITLE
Set file permissions to 0o500 when the workspace is read-only on linux

### LINKED ISSUE #9389: [🐛 | Bug]: Mountpoint show write perm when user as the Reader profile
### Parsec version tested on:

3.2.4-rc.2

### Platforms tested on:

Linux

### Bug description:

1. Have parsec with a workspace where you are `reader`
2. In the explorer, go to the mountpoint of the workspace 
3. Observe that the mountpoint folder and its children have the permission `0o700` (where it should be `0o500`)

### Relevant output:

_No response_

### PR DESCRIPTION
**Pull request by vxgmichel**
Fix #9389

### CODE REVIEW

File: libparsec/crates/platform_mountpoint/src/unix/filesystem.rs [hunk 1]
```diff
@@ -120,25 +143,57 @@ fn entry_stat_to_file_attr(stat: EntryStat, inode: Inode, uid: u32, gid: u32) ->
     }
 }
 
+enum MaybeReadOnly {
+    ReadOnlyMountpoint,
+    ReadWriteMountpoint,
+}
+
+impl MaybeReadOnly {
+    fn get(&self, ops: &WorkspaceOps) -> bool {
```
Comment (touilleMan) [inline libparsec/crates/platform_mountpoint/src/unix/filesystem.rs:152]: It is not needed to check the current role since access control is done when calling the workspace ops methods, instead we can just rely on the `is_read_only` computed once at mountpoint start, and return the correct error when workspace ops return a not allowed error code

File: libparsec/crates/platform_mountpoint/src/unix/filesystem.rs [hunk 2]
```diff
@@ -35,17 +35,29 @@ const GENERATION: u64 = 0;
...
+const READ_ONLY_PERMISSIONS: u16 = 0o500;
 
 fn os_name_to_entry_name(name: &OsStr) -> EntryNameResult<EntryName> {
     name.to_str()
         .map(|s| s.parse())
         .ok_or(EntryNameError::InvalidName)?
 }
 
-fn file_stat_to_file_attr(stat: FileStat, inode: Inode, uid: u32, gid: u32) -> fuser::FileAttr {
+fn file_stat_to_file_attr(
```
Comment (touilleMan) [inline libparsec/crates/platform_mountpoint/src/unix/filesystem.rs:47]: you can move this function (and `entry_stat_to_file_attr` & `reply_with_lookup`) as `Filesystem` methods if you think it is simpler/cleaner to have `self.is_read_only` (hence not having to modify the call sites) instead of passing it as parameter

**Review by touilleMan — APPROVED** [review]

File: libparsec/crates/platform_mountpoint/src/unix/filesystem.rs [hunk 3]
```diff
@@ -35,17 +35,29 @@ const GENERATION: u64 = 0;
 const BLOCK_SIZE: u64 = 512 * 1024;
 /// Default permissions for files and folders.
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_mountpoint/src/unix/filesystem.rs:36]: **nitpick:** Comment not up-to-date

File: libparsec/crates/platform_mountpoint/src/unix/filesystem.rs (hunk 1 above)
Comment (vxgmichel) [reply libparsec/crates/platform_mountpoint/src/unix/filesystem.rs]: 28a6bdf858bce7419dfadb38c812d9f486d02aa7

File: libparsec/crates/platform_mountpoint/src/unix/filesystem.rs (hunk 3 above)
Comment (vxgmichel) [reply libparsec/crates/platform_mountpoint/src/unix/filesystem.rs]: 28a6bdf858bce7419dfadb38c812d9f486d02aa7

File: libparsec/crates/platform_mountpoint/src/unix/filesystem.rs (hunk 2 above)
Comment (vxgmichel) [reply libparsec/crates/platform_mountpoint/src/unix/filesystem.rs:49]: I don't think we can due to the use of `self.tokio_handle.spawn(async move { ... })`

File: libparsec/crates/platform_mountpoint/src/unix/filesystem.rs [hunk 4]
```diff
@@ -33,19 +33,33 @@ const TTL: std::time::Duration = std::time::Duration::ZERO;
 const GENERATION: u64 = 0;
 /// The default block size, set to 512 KB.
 const BLOCK_SIZE: u64 = 512 * 1024;
-/// Default permissions for files and folders.
+/// Read-write permissions for files and folders.
 /// Equivalent to `chmod` flags `all=,u=rwx`.
-const PERMISSIONS: u16 = 0o700;
+const READ_WRITE_PERMISSIONS: u16 = 0o700;
+/// Read-only permissions for files and folders.
+/// Equivalent to `chmod` flags `all=,u=r.x`.
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_mountpoint/src/unix/filesystem.rs:40]: **nitpick:** 
```suggestion
/// Equivalent to `chmod` flags `all=,u=rx`.
```

File: newsfragments/9389.bugfix.rst [hunk 5]
```diff
@@ -0,0 +1 @@
+Do not report write permissions on linux when a workspace is read-only.
```
Comment (FirelightFlagboy) [inline newsfragments/9389.bugfix.rst:1]: **nitpick:** macOS is also affected

```suggestion
Do not report write permissions on unix when a workspace is read-only.
```

```suggestion
Do not report write permissions on linux and macOS when a workspace is read-only.
```

Comment (vxgmichel) [reply newsfragments/9389.bugfix.rst]: 0ae9e99bf9934842c99122f10fd2199d9e174ae1

File: libparsec/crates/platform_mountpoint/src/unix/filesystem.rs (hunk 4 above)
Comment (vxgmichel) [reply libparsec/crates/platform_mountpoint/src/unix/filesystem.rs]: 3d9870f5c3b89fb553ce0aacf705ca9adb5f690d
