### PR TITLE
[MS] Fix back button responsive on Parsec Account

### LINKED ISSUE #11092: [MS] Create account visual back button negative offset
### Parsec version

web

### Which platform(s) you have observed the problem

- [x] Any
- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Web

### Bug description

The back button is displayed as cropped.

### Reproduction steps

```bash
Go to "Create account" on login page.
```

### Relevant output:

Image

### PR DESCRIPTION
**Pull request by fabienSvtr**
image

Closes #11092

### CODE REVIEW

File: client/src/views/account/CreateAccountPage.vue [hunk 1]
```diff
@@ -309,6 +359,7 @@ async function goToHome(): Promise<void> {
 }
 
 async function goToLogin(): Promise<void> {
+  await menuController.close();
```
Comment (Max-7) [inline client/src/views/account/CreateAccountPage.vue]: Why adding that?
There are some bugs with the menu when you switch pages, it stops opening. Probably linked to the calls to `close()`.

File: client/src/views/home/AccountHomePage.vue [hunk 2]
```diff
@@ -138,10 +155,13 @@ async function onSkipClicked(): Promise<void> {
 }
 
 async function goToCreateAccount(): Promise<void> {
+  console.log(menuController);
```
Comment (Ironicbay) [inline client/src/views/home/AccountHomePage.vue]: Log to remove

File: client/src/views/account/CreateAccountPage.vue [hunk 3]
```diff
@@ -237,13 +294,22 @@ const validAuth = asyncComputed(async () => {
...
 
+onIonViewWillLeave(async () => {
+  onLeavePage.value = true;
+});
+
+function showBackButton(): boolean {
+  return step.value === Steps.UserInformation || step.value === Steps.Code || step.value === Steps.Authentication;
+}
+
 async function back(): Promise<void> {
```
Comment (Ironicbay) [inline client/src/views/account/CreateAccountPage.vue:317]: Not related but it spares us an issue and additional PR: please add
```
    error.value = '';
```
in the `else` block of this function, next to the code validation clear.

File: client/src/views/account/CreateAccountPage.vue [hunk 4]
```diff
@@ -212,6 +268,7 @@ const querying = ref(false);
 const choosePasswordRef = useTemplateRef<InstanceType<typeof MsChoosePasswordInput>>('choosePassword');
 const refreshKey = ref(0);
 const code = ref<Array<string>>([]);
+const onLeavePage = ref(false);
```
Comment (Ironicbay) [inline client/src/views/account/CreateAccountPage.vue:275]: What's the point of this variable?

File: client/src/views/home/AccountHomePage.vue [hunk 5]
```diff
@@ -138,10 +155,13 @@ async function onSkipClicked(): Promise<void> {
...
+  await menuController.close();
```
Comment (Ironicbay) [inline client/src/views/home/AccountHomePage.vue]: What does this function do and why is it needed?

Comment (fabienSvtr) [reply client/src/views/home/AccountHomePage.vue]: To close the menu when changing pages, but it closes anyway when we leave the page. I simply forgot to remove it.

File: client/src/views/account/CreateAccountPage.vue (hunk 4 above)
Comment (fabienSvtr) [reply client/src/views/account/CreateAccountPage.vue:275]: We are encountering an issue when opening the menu from LoginPage or CreateAccountPage. If we open from one of these pages and move to the other page, clicking on the menu button opens the menu on the previous page. So I simply added some information to the page to tell the router that we have left the page. This way, the menu can be opened on the other page.

Comment (fabienSvtr) [reply client/src/views/account/CreateAccountPage.vue:275]: I add a comment to explain.

File: client/src/views/home/AccountHomePage.vue [hunk 6]
```diff
@@ -142,6 +159,7 @@ async function goToCreateAccount(): Promise<void> {
 }
 
 async function goToCustomerArea(): Promise<void> {
+  await menuController.close();
```
Comment (Ironicbay) [inline client/src/views/home/AccountHomePage.vue]: You left this call as well, might not be needed
