### PR TITLE
[MS] Handle libparsec load error at startup

### LINKED ISSUE #8613: [🐛 | Bug]: Handle error if macFUSE isn't installed
### Parsec version tested on:

3.0.3

### Platforms tested on:

MacOS

### Bug description:

If macFUSE isn't installed, the app opens to a black screen, failing to find `libfuse.2.dylib`. 

### Relevant output:

screenshot_2024-10-04_at_09 05 25

### PR DESCRIPTION
**Pull request by Max-7**
Closes #8613 

- [X] Keep changes in the pull request as small as possible
- [X] Ensure the commit history is sanitized
- [X] Give a meaningful title to your PR
- [X] Describe your changes
- [X] Link any related issue in the description

### CODE REVIEW

File: client/electron/src/index.ts [hunk 1]
```diff
@@ -215,3 +217,28 @@ ipcMain.on(PageToWindowChannel.OpenConfigDir, async () => {
 ipcMain.on(PageToWindowChannel.AuthorizeURL, async (_event, url: string) => {
   myCapacitorApp.addAuthorizedURL(url);
 });
+
+ipcMain.on(PageToWindowChannel.MacfuseNotInstalled, async (_event) => {
+  const locale = app.getLocale();
+  const url = locale.startsWith('fr') ? INSTALL_GUIDE_URL_FR : INSTALL_GUIDE_URL_EN;
```
Comment (FirelightFlagboy) [inline client/electron/src/index.ts:223]: Create a single constant `isFRLocale` and use it everywhere

**Review by Ironicbay — APPROVED** [review]
