### PR TITLE
[MS] Visual bugs ionic 8

### LINKED ISSUE #10709: [MS] Visual bugs on Ionic 8 (web release)
### Bug 1
Image

### Bug 2
Image

### Bug 3
Image

### Bug 4
https://github.com/user-attachments/assets/e9a0ec75-1429-4b1d-b254-89e2a7f8b14c

### Bug 5
Image

### PR DESCRIPTION
**Pull request by fabienSvtr**
## Describe your changes

- Fix the hover effect on secondary-menu item
- Replace `ion-label` by `ion-text` to avoid errors (not throughout the whole app)
- Replace `ion-buttons` by a `div` because Ionic adds classes causing many visual issues
- Fix the shadow added by Ionic 8 on `ion-header` and `ion-footer`
- Fix visual issues with popover (element height)
- Add transparent background to the container in the sidebar menu.
- Remove Android highlight (border-bottom while clicking on input)
- Update logo size for custom branding

## Checklist

Before you submit this pull request, please make sure to:

- [ ] Keep changes in the pull request as small as possible
   
- [ ] Ensure the commit history is sanitized
   
- [ ] Give a meaningful title to your PR
- [ ] Describe your changes
   
- [ ] Link any related issue in the description
   
- [ ] Link any dependent pull request in the description

closes #10709

### CODE REVIEW

File: client/src/components/small-display/SmallDisplayCategoryFileContextMenu.vue [hunk 1]
```diff
@@ -18,9 +18,9 @@
             class="ion-no-padding list-group-item"
           >
             <ion-icon :icon="checkmarkCircle" />
-            <ion-label class="button-large list-group-item__label-small">
+            <ion-text class="button-large list-group-item__label-small">
```
Comment (Ironicbay) [inline client/src/components/small-display/SmallDisplayCategoryFileContextMenu.vue:24]: This option text color seems to be #000000 
Screenshot 2025-07-15 at 14 22 39

File: client/src/components/small-display/SmallDisplayFileContextMenu.vue
Comment (Ironicbay) [inline client/src/components/small-display/SmallDisplayFileContextMenu.vue:1]: Text color seems to be #000000 as well
Screenshot 2025-07-15 at 14 23 22

File: client/src/components/small-display/SmallDisplayUserContextMenu.vue
Comment (Ironicbay) [inline client/src/components/small-display/SmallDisplayUserContextMenu.vue:1]: Same issue
Screenshot 2025-07-15 at 14 29 11

File: client/src/components/users/UserSelectDropdown.vue
Comment (Ironicbay) [inline client/src/components/users/UserSelectDropdown.vue:1]: `UserSelect.vue` needs to be updated as well (input field)
Screenshot 2025-07-15 at 14 34 40

File: client/src/views/devices/GreetDeviceModal.vue
Comment (Ironicbay) [inline client/src/views/devices/GreetDeviceModal.vue:1]: `SasCodeChoice.vue` hover is broken
Screenshot 2025-07-15 at 14 43 34

Comment (Ironicbay) [reply client/src/views/devices/GreetDeviceModal.vue:1]: Again for `SasCodeChoice.vue`, bottom button text color seems to be #000000
Screenshot 2025-07-15 at 14 44 24

File: client/src/views/workspaces/SmallDisplayWorkspaceContextMenu.vue
Comment (Ironicbay) [inline client/src/views/workspaces/SmallDisplayWorkspaceContextMenu.vue:1]: Missing text color

Screenshot 2025-07-15 at 15 05 12

**Review by Ironicbay — CHANGES_REQUESTED** [review]

**Review by Ironicbay — APPROVED** [review]
