### PR TITLE
Oxidation replace `WorkspaceStorage` & `WorkspaceStorageSnapshot` & `UserStorage`

### LINKED ISSUE #2864: Flaky hypothesis test `tests/core/test_sync_monitor_stateful.py::test_sync_monitor_stateful`
The hypothesis test during the action [2887918745](https://github.com/Scille/parsec-cloud/actions/runs/2887918745) failed because of that.

The log trace is contain in [macos-hypothesis-test.zip](https://github.com/Scille/parsec-cloud/files/9380445/macos-hypothesis-test.zip)

### LINKED ISSUE #2898: Oxidation `storage` module
Oxidize the module at `oxidation/libparsec_python/src/storage.rs`

Migrating:

- `WorkspaceStorage`
- `WorkspaceStorageSnapshot`
- `UserStorage`

### LINKED ISSUE #3168: Oxidize `UserStorage`
`UserStorage` depends on `ManifestStorage` so to simplify the migration.
I suggest we first migrate `ManifestStorage` (tracked in #3169) then migrate `UserStorage`

# TODOs

- [ ] Remove the dependency on the python class `ManifestStorage` (the class in implemented in Rust but not binded see #3169)
- [ ] Replace the python class `UserStorage` with the Rust one using `pyo3`
- [ ] Correct the fixture `initialize_local_user_manifest` at `tests/fixtures.py`
- [ ] Correct the fixture `initialize_local_user_manifest` at `tests/common/binder.py`
- [ ] Correct the fixture `alice_user_storage` at `tests/core/fs/storage/test_user_storage.py`
- [ ] Correct the test `test_initialization` at `tests/core/fs/storage/test_user_storage.py` 
- [ ] Correct the test `test_storage_file_tree` at `tests/core/fs/storage/test_user_storage.py`

### LINKED ISSUE #3169: Oxidize `ManifestStorage`
# TODOs

- [ ] include change from #3224
- [ ] Replace the python class by the Rust one using `pyo3`
- [ ] Correct the test `test_workspace_manifest_access_while_speculative` at `tests/core/fs/test_bootstrap.py`

### LINKED ISSUE #3170: Remove `LocalDatabase` after oxidation
Remove the python class `LocalDatabase` after oxidation of the last classes that where using it. 

# Depend on 

- #3168 
- #3169 

# TODOs

- [ ] Remove the class `LocalDatabase`
- [ ] Rewrite the suite tests `test_disk_full` at `tests/core/fs/test_disk_full.py`
- [ ] Rewrite the test `test_workspace_manifest_access_while_speculative` at `tests/core/fs/test_bootstrap.py`
- [ ] Rewrite the fixture `persistent_mockup` at `tests/conftest.py`

> Reminder the goal of the rewrite is to not have the class `LocalDatabase` defined in the python code base.

### LINKED ISSUE #3836: [Rust] Make local database call async
> As we discussed yesterday, we need to encapsulate the sqlite part away from the business logic (given we have to support web). 
> So it seems the right move to have this encapsulation defining an async API, and to implement it as a simple thread-per-connection with message passing in the sqlite implementation (the web one relying on browser API, they are already async by default)

_Originally posted by @touilleMan in https://github.com/Scille/parsec-cloud/pull/3766#discussion_r1061279370_

### PR DESCRIPTION
**Pull request by FirelightFlagboy**
- Oxidize `WorkspaceStorage`.
- Oxidize `WorkspaceStorageSnapshot`.
- Oxidize `workspace_storage_non_speculative_init`
- Type some tests (the typed tests where those that failed during the migration).
- Correct some tests to work with the oxidation.
- Rename `WorkspaceStorageTimestamped` to `WorkspaceStorageSnapshot`.

## TODOs

- [x] use the change from #3224
  - [x] fix `test_database_with_invalid_pattern_resilience` in `tests/core/fs/workspacefs/test_confinement.py`
    - [x] Directly modify the database to insert an invalid regex string
- [x] use the change from #3523 
  - [x] On the rust side we need to close every sqlite connection  

closes #3836, closes #3170, closes #3169, closes #3168, closes #2898, closes #2864

### CODE REVIEW

File: src/workspace_storage.rs [hunk 1]
```diff
@@ -533,6 +533,9 @@ pub(crate) fn workspace_storage_non_speculative_init(
 fn fs_to_python_error(e: FSError) -> PyErr {
     match e {
         FSError::DatabaseQueryError(_) => FSLocalStorageOperationError::new_err(e.to_string()),
+        FSError::NoSpaceLeftOnDevice => {
+            FSLocalStorageOperationError::new_err("database or disk is full".to_string())
```
Comment (FirelightFlagboy) [inline src/workspace_storage.rs:537]:
```suggestion
FSLocalStorageOperationalError::new_err("database or disk is full".to_string())
```

File: oxidation/libparsec/crates/core_fs/src/storage/local_database.rs [hunk 2]
```diff
@@ -1,48 +1,150 @@
...
         // to 15 ms the default mode) but still protects the database against
         // corruption in the case of OS crash or power failure.
-        conn.batch_execute(
-            "
+        connection
+            .batch_execute(
+                "
             PRAGMA journal_mode = WAL; -- better write-concurrency
             PRAGMA synchronous = NORMAL; -- fsync only in critical moments
         ",
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/core_fs/src/storage/local_database.rs:43]: Can you indent correctly ?

File: oxidation/libparsec/crates/core_fs/src/storage/local_database.rs [hunk 3]
```diff
@@ -1,48 +1,150 @@
...
+}
+
+impl<'a> From<MutexGuard<'a, Option<SqliteConnection>>> for LockedSqliteConnection<'a> {
+    fn from(guard: MutexGuard<'a, Option<SqliteConnection>>) -> Self {
+        Self { conn: guard }
+    }
+}
+
+impl<'a> LockedSqliteConnection<'a> {
+    #[inline]
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/core_fs/src/storage/local_database.rs:97]: Why do you want to force `inlining` ?

File: oxidation/libparsec/crates/core_fs/src/storage/local_database.rs [hunk 4]
```diff
@@ -1,48 +1,150 @@
...
+            Err(err @ diesel::result::Error::DatabaseError(_, _)) => {
+                *self.conn = None;
+                Err(ExecError::Internal(FSError::from(err)))
+            }
+            Err(e) => Err(ExecError::DieselError(e)),
+            Ok(ok) => Ok(ok),
+        }
+    }
+
+    #[inline]
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/core_fs/src/storage/local_database.rs:117]: Same

File: oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs [hunk 5]
```diff
@@ -111,120 +123,116 @@ impl Drop for ManifestStorage {
...
+        )?;
         // Singleton storing the checkpoint
-        sql_query(
-            "CREATE TABLE IF NOT EXISTS realm_checkpoint (
+        conn.exec_with_handler(
+            |conn| {
+                sql_query(
+                    "CREATE TABLE IF NOT EXISTS realm_checkpoint (
               _id INTEGER PRIMARY KEY NOT NULL,
               checkpoint INTEGER NOT NULL
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs:162]: Same

File: oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs [hunk 6]
```diff
@@ -111,120 +123,116 @@ impl Drop for ManifestStorage {
...
+            },
+            |e| FSError::CreateTable(format!("realm_checkpoint {e}")),
+        )?;
         // Singleton storing the prevent_sync_pattern
-        sql_query(
-            "CREATE TABLE IF NOT EXISTS prevent_sync_pattern (
+        conn.exec_with_handler(
+            |conn| {
+                sql_query(
+                    "CREATE TABLE IF NOT EXISTS prevent_sync_pattern (
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs:173]: Same

File: oxidation/libparsec/crates/core_fs/src/storage/local_database.rs [hunk 7]
```diff
@@ -1,48 +1,150 @@
...
+    pub fn exec<T, F>(&self, f: F) -> Result<T, ExecError>
+    where
+        F: FnOnce(&mut SqliteConnection) -> Result<T, diesel::result::Error>,
+    {
+        self.lock_connection().exec(f)
+    }
+
+    #[inline]
+    pub fn exec_with_handler<T, F, G>(&self, f: F, error_handler: G) -> FSResult<T>
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/core_fs/src/storage/local_database.rs:69]: Why do we need this, instead of `self.exec()?;` ?

File: parsec/backend/postgresql/realm_queries/maintenance.py [hunk 8]
```diff
@@ -38,7 +38,6 @@
     RealmStatus,
 )
 
-
```
Comment (TimeEngineer) [inline parsec/backend/postgresql/realm_queries/maintenance.py:41]: Why do you change the linter in the same PR ?
Many files are modified for no reason :/

File: parsec/core/sync_monitor.py [hunk 9]
```diff
@@ -3,12 +3,13 @@
 
 import math
 from collections import defaultdict
-from typing import TYPE_CHECKING, Any, Dict, Iterable, Union, cast
+from typing import TYPE_CHECKING, Any, Iterable, Union, cast
```
Comment (TimeEngineer) [inline parsec/core/sync_monitor.py:6]: And `Union` ?

File: src/workspace_storage.rs [hunk 10]
```diff
@@ -0,0 +1,545 @@
...
+
+import_exception!(parsec.core.fs.exceptions, FSLocalMissError);
+import_exception!(parsec.core.fs.exceptions, FSInvalidFileDescriptor);
+import_exception!(parsec.core.fs.exceptions, FSLocalStorageOperationalError);
+import_exception!(parsec.core.fs.exceptions, FSLocalStorageClosedError);
+import_exception!(parsec.core.fs.exceptions, FSInternalError);
+
+/// WorkspaceStorage's binding is implemented with allow_threads because its
+/// methods are called in trio.to_thread to connect the sync and async world
+#[pyclass(module = "parsec._parsec")]
```
Comment (TimeEngineer) [inline src/workspace_storage.rs:32]: is `module` necessary ?

File: src/workspace_storage.rs [hunk 11]
```diff
@@ -0,0 +1,545 @@
...
+    fn new(
+        data_base_dir: &PyAny,
+        device: LocalDevice,
+        workspace_id: EntryID,
+        prevent_sync_pattern: Regex,
+        cache_size: u64,
+        data_vacuum_threshold: Option<u64>,
+    ) -> PyResult<Self> {
+        let data_base_dir =
+            PathBuf::from(data_base_dir.call_method0("__str__")?.extract::<String>()?);
```
Comment (TimeEngineer) [inline src/workspace_storage.rs:50]: You can extract &str, if you don't need ownership

File: src/workspace_storage.rs [hunk 12]
```diff
@@ -0,0 +1,545 @@
...
+    fn is_manifest_cache_ahead_of_persistance(
+        &self,
+        py: Python,
+        entry_id: EntryID,
+    ) -> PyResult<bool> {
+        Ok(py.allow_threads(|| self.0.is_manifest_cache_ahead_of_persistance(&entry_id.0)))
+    }
+}
+
+#[pyclass(module = "parsec._parsec")]
```
Comment (TimeEngineer) [inline src/workspace_storage.rs:363]: needed ?

File: tests/common/binder.py [hunk 13]
```diff
@@ -3,7 +3,7 @@
 
 from dataclasses import dataclass
 from functools import partial
-from typing import Optional, Tuple, Union
+from typing import Dict, Optional, Tuple, Union
```
Comment (TimeEngineer) [inline tests/common/binder.py:6]: Don't import Dict

File: tests/common/freeze_time.py [hunk 14]
```diff
@@ -2,24 +2,24 @@
 from __future__ import annotations
 
 from contextlib import contextmanager
+from typing import Dict, Optional, Union
```
Comment (TimeEngineer) [inline tests/common/freeze_time.py:5]: Don't

File: tests/core/fs/old_workspace_storage.py [hunk 15]
```diff
@@ -0,0 +1,803 @@
+# Parsec Cloud (https://parsec.cloud) Copyright (c) AGPL-3.0 2016-present Scille SAS
```
Comment (TimeEngineer) [inline tests/core/fs/old_workspace_storage.py:1]: Why should it be kept ?

File: tests/core/gui/test_workspaces_reencrypt.py [hunk 16]
```diff
@@ -121,17 +133,18 @@ def _reencrypt_button_displayed():
 
 @pytest.mark.gui
 @pytest.mark.trio
+@pytest.mark.flaky(reruns=3)
```
Comment (TimeEngineer) [inline tests/core/gui/test_workspaces_reencrypt.py:136]: Why is it flacky now ?

File: tests/fixtures.py [hunk 17]
```diff
@@ -1,959 +0,0 @@
-# Parsec Cloud (https://parsec.cloud) Copyright (c) AGPL-3.0 2016-present Scille SAS
```
Comment (TimeEngineer) [inline tests/fixtures.py:1]: Wow.

File: oxidation/libparsec/crates/core_fs/src/storage/local_database.rs (hunk 2 above)
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/local_database.rs:43]: done

Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/local_database.rs:43]: done

File: oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs (hunk 5 above)
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs:162]: done

File: oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs (hunk 6 above)
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs:173]: done

File: tests/core/gui/test_workspaces_reencrypt.py (hunk 16 above)
Comment (FirelightFlagboy) [reply tests/core/gui/test_workspaces_reencrypt.py:136]: :shrug: dunno but It can fail sometime and slow me down that why I marked it flaky

File: tests/fixtures.py (hunk 17 above)
Comment (FirelightFlagboy) [reply tests/fixtures.py:1]: As expected since `tests/fixtures.py` is legacy code that should not be used

File: oxidation/libparsec/crates/core_fs/src/storage/local_database.rs (hunk 4 above)
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/local_database.rs:117]: Will use https://github.com/Scille/parsec-cloud/pull/2903#discussion_r1042349149 as a reference

File: oxidation/libparsec/crates/core_fs/src/storage/local_database.rs (hunk 3 above)
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/local_database.rs:97]: I don't force the `inlining` of the method see <https://doc.rust-lang.org/reference/attributes/codegen.html#the-inline-attribute>

Why I use `inline` 
> Before this PR the logic to access the wrapped connection was present on every object that used `SqliteConn`

Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/local_database.rs:97]: PS: It may be better to let the compiler judge if this method is best to be inlined or not, I will remove this attribute

File: oxidation/libparsec/crates/core_fs/src/storage/local_database.rs (hunk 7 above)
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/local_database.rs:69]: Because sometime we want to manually handle the database error, and we better refactor it latter

File: oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs [hunk 18]
```diff
@@ -378,219 +409,279 @@ impl ManifestStorage {
...
+            .caches
+            .lock()
+            .expect("Mutex is poisoned")
+            .get(&entry_id)
+            .cloned()
+        {
+            self.ensure_manifest_persistent_lock(entry_id, cache_entry)
+        } else {
+            Ok(())
+        }
```
[the remark this answers is not in the document]
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs:505]: I also prefer this pattern but on longer function that need quick exit

File: parsec/core/sync_monitor.py (hunk 9 above)
Comment (FirelightFlagboy) [reply parsec/core/sync_monitor.py:6]: done

File: tests/common/binder.py (hunk 13 above)
Comment (FirelightFlagboy) [reply tests/common/binder.py:6]: done

File: src/workspace_storage.rs (hunk 11 above)
Comment (FirelightFlagboy) [reply src/workspace_storage.rs:50]: done

File: src/workspace_storage.rs (hunk 12 above)
Comment (FirelightFlagboy) [reply src/workspace_storage.rs:363]: I don't think so I removed it

File: src/workspace_storage.rs [hunk 19]
```diff
@@ -0,0 +1,545 @@
...
+/// methods are called in trio.to_thread to connect the sync and async world
+#[pyclass(module = "parsec._parsec")]
+#[derive(Clone)]
+pub(crate) struct WorkspaceStorage(pub libparsec::core_fs::WorkspaceStorage, pub Option<Regex>);
+
+#[pymethods]
+impl WorkspaceStorage {
+    #[new]
+    #[args(cache_size = "512 * 1024 * 1024")]
+    #[allow(unused_variables)]
```
[the remark this answers is not in the document]
Comment (FirelightFlagboy) [reply src/workspace_storage.rs:40]: done

File: oxidation/libparsec/crates/core_fs/src/storage/local_database.rs [hunk 20]
```diff
@@ -1,48 +1,150 @@
...
-use crate::error::{FSError, FSResult};
+use diesel::{connection::SimpleConnection, Connection, SqliteConnection};
 
-// https://www.sqlite.org/limits.html
-// #9 Maximum Number Of Host Parameters In A Single SQL Statement
+use std::{
+    ops::DerefMut,
+    path::PathBuf,
+    sync::{Arc, Mutex, MutexGuard},
+};
```
[the remark this answers is not in the document]
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/local_database.rs:11]: done

File: parsec/backend/postgresql/realm_queries/maintenance.py (hunk 8 above)
Comment (FirelightFlagboy) [reply parsec/backend/postgresql/realm_queries/maintenance.py]: Should be better now

File: oxidation/libparsec/crates/core_fs/src/storage/local_database.rs (hunk 3 above)
Comment (TimeEngineer) [reply oxidation/libparsec/crates/core_fs/src/storage/local_database.rs]: The request is >> inlining optimization...

File: oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs (hunk 18 above)
[the remark this answers is not in the document]
Comment (TimeEngineer) [reply oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs:505]: And why not there ?

**Review by TimeEngineer — APPROVED** [review]

**Comment by TimeEngineer** [comment]
/!\ Remember `old_workspace_storage`

File: .github/workflows/ci.yml [hunk 21]
```diff
@@ -300,7 +300,7 @@ jobs:
           steps.python-changes.outputs.run == 'true'
           && startsWith(matrix.os, 'macos-') != true
         run: poetry run pytest ${{ env.pytest-base-args }} tests --runmountpoint --runslow --rungui -m gui
-        timeout-minutes: 10
+        timeout-minutes: 20
```
Comment (TimeEngineer) [inline .github/workflows/ci.yml:303]: same

File: .github/workflows/ci.yml [hunk 22]
```diff
@@ -287,7 +287,7 @@ jobs:
           steps.python-changes.outputs.run == 'true'
           && startsWith(matrix.os, 'macos-') != true
         run: poetry run pytest ${{ env.pytest-base-args }} tests --runmountpoint --runslow -m mountpoint
-        timeout-minutes: 10
+        timeout-minutes: 20
```
Comment (TimeEngineer) [inline .github/workflows/ci.yml:290]: Can you rollback this change ?

File: oxidation/libparsec/crates/core_fs/Cargo.toml [hunk 23]
```diff
@@ -15,13 +15,18 @@ libparsec_client_types = { path = "../client_types" }
 # Disable Diesel's default feature to remove `32-column-tables` which slowdown compilation
 # quiet a lot (Diesel crate compilation on my machine: 19s with vs 8s without).
 # Note this is fine as long as we use tables with at most 16 columns.
-diesel = { version = "2.0.2", features = ["sqlite", "r2d2", "with-deprecated"], default-features = false }
+diesel = { version = "2.0.2", features = ["sqlite"], default-features = false }
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/core_fs/Cargo.toml:18]: `with-deprecated` doesn't accelerate build ?

File: oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs [hunk 24]
```diff
@@ -35,73 +35,91 @@ struct NewChunk<'a> {
...
-            );",
-        )
-        .execute(conn)
-        .map_err(|e| FSError::CreateTable(format!("chunks {e}")))?;
+    async fn create_db(&self) -> FSResult<()> {
+        self.conn()
+            .exec(|conn| {
+                sql_query(
+                    "CREATE TABLE IF NOT EXISTS chunks (
+                    chunk_id BLOB PRIMARY KEY NOT NULL, -- UUID
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs:49]: Indentation

File: oxidation/libparsec/crates/platform_local_db/Cargo.toml [hunk 25]
```diff
@@ -0,0 +1,24 @@
...
+# Enable to open database in memory.
+test-utils = ["lazy_static"]
+
+[dependencies]
+async-trait = "0.1.61"
+tokio = { version = "1.24.1", features = ["fs", "sync"] }
+thiserror = "1.0.37"
+diesel = { version = "2.0.2", features = ["sqlite"], default-features = false }
+libsqlite3-sys = { version = "0.25.2", features = ["bundled"] }
+platform_async = { path = "../platform_async", package = "libparsec_platform_async"}
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/platform_local_db/Cargo.toml:18]: why `package` ?

File: oxidation/libparsec/crates/platform_local_db/src/lib.rs [hunk 26]
```diff
@@ -0,0 +1,153 @@
...
+        let executor = SqliteExecutor::spawn(conn);
+        Ok(Self {
+            executor: Arc::new(RwLock::new(Some(executor))),
+        })
+    }
+}
+
+async fn new_sqlite_connection_from_path(path: &str) -> Result<SqliteConnection, DatabaseError> {
+    if let Some(prefix) = PathBuf::from(path).parent() {
+        // TODO: Create path in async mode with tokio
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/platform_local_db/src/lib.rs:60]: Do it ?

File: oxidation/libparsec/crates/platform_local_db/src/lib.rs [hunk 27]
```diff
@@ -0,0 +1,153 @@
...
+                prefix
+                    .to_str()
+                    .expect("We generate the Path from a `&str` so UTF-8 is already checked")
+            ))
+        })?;
+    }
+    let mut connection = SqliteConnection::establish(path)?;
+    connection.batch_execute(
+        "
+        PRAGMA journal_mode = WAL; -- better write-concurrency
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/platform_local_db/src/lib.rs:74]: Indentation

File: parsec/_parsec_pyi/storage/user_storage.pyi [hunk 28]
```diff
@@ -0,0 +1,26 @@
+from __future__ import annotations
```
Comment (TimeEngineer) [inline parsec/_parsec_pyi/storage/user_storage.pyi:1]: Header

File: parsec/_parsec_pyi/storage/workspace_storage.pyi [hunk 29]
```diff
@@ -0,0 +1,95 @@
+from __future__ import annotations
```
Comment (TimeEngineer) [inline parsec/_parsec_pyi/storage/workspace_storage.pyi:1]: Header

**Review by TimeEngineer — CHANGES_REQUESTED** [review]

File: oxidation/libparsec/crates/core_fs/Cargo.toml (hunk 23 above)
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/Cargo.toml:18]: Why would it should ?

File: oxidation/libparsec/crates/platform_local_db/Cargo.toml (hunk 25 above)
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/platform_local_db/Cargo.toml:18]: To be able to have a smaller name

File: parsec/_parsec_pyi/storage/user_storage.pyi (hunk 28 above)
Comment (FirelightFlagboy) [reply parsec/_parsec_pyi/storage/user_storage.pyi:1]: `Pre-commit` don't complain :eyes:

File: oxidation/libparsec/crates/core_fs/Cargo.toml (hunk 23 above)
Comment (TimeEngineer) [reply oxidation/libparsec/crates/core_fs/Cargo.toml:18]: I don't remember why we add this feature

File: parsec/_parsec_pyi/storage/user_storage.pyi (hunk 28 above)
Comment (TimeEngineer) [reply parsec/_parsec_pyi/storage/user_storage.pyi:1]: `pre-commit` should be updated

File: oxidation/libparsec/crates/core_fs/Cargo.toml (hunk 23 above)
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/Cargo.toml:18]: Nether do I :shrug:

Comment (TimeEngineer) [reply oxidation/libparsec/crates/core_fs/Cargo.toml:18]: @touilleMan https://github.com/Scille/parsec-cloud/pull/3759

Comment (TimeEngineer) [reply oxidation/libparsec/crates/core_fs/Cargo.toml:18]: `with-deprecated` or `default-features=false` which speed up ?

File: oxidation/libparsec/crates/platform_local_db/src/lib.rs (hunk 27 above)
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/platform_local_db/src/lib.rs]: done

File: parsec/_parsec_pyi/storage/user_storage.pyi (hunk 28 above)
Comment (FirelightFlagboy) [reply parsec/_parsec_pyi/storage/user_storage.pyi:3]: done

File: parsec/_parsec_pyi/storage/workspace_storage.pyi (hunk 29 above)
Comment (FirelightFlagboy) [reply parsec/_parsec_pyi/storage/workspace_storage.pyi:3]: done

File: oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs [hunk 30]
```diff
@@ -378,252 +447,376 @@ impl ManifestStorage {
...
+                .expect("RwLock is poisoned")
+                .has_chunk_to_be_flush()
+        });
+
+        if let Some(fut) = result {
+            fut.await
+        } else {
+            false
+        }
+    }
```
Comment (FirelightFlagboy) [inline oxidation/libparsec/crates/core_fs/src/storage/manifest_storage.rs:729]: Since this method don't have `await` block make it sync.

File: .github/workflows/ci.yml (hunk 21 above)
Comment (FirelightFlagboy) [reply .github/workflows/ci.yml]: done

File: .github/workflows/ci.yml (hunk 22 above)
Comment (FirelightFlagboy) [reply .github/workflows/ci.yml]: done

File: src/storage/mod.rs [hunk 31]
```diff
@@ -0,0 +1,109 @@
...
+
+    Ok(manifest)
+}
+
+pub(crate) fn manifest_into_py_object(
+    manifest: libparsec::client_types::LocalManifest,
+) -> PyObject {
+    match manifest.try_into() {
+        Ok(manifest) => file_or_folder_manifest_into_py_object(manifest),
+        Err(manifest) => user_or_workspace_manifest_into_py_object(manifest),
```
Comment (TimeEngineer) [inline src/storage/mod.rs:81]: Try another function, this is not clear why `file` or `folder` should be ok and not `user` or `workspace`, maybe `try_from` ?

File: src/storage/user_storage.rs [hunk 32]
```diff
@@ -0,0 +1,154 @@
+// Parsec Cloud (https://parsec.cloud) Copyright (c) BUSL-1.1 (eventually AGPL-3.0) 2016-present Scille SAS
+
+use std::{
+    collections::{HashMap, HashSet},
+    path::PathBuf,
+    sync::{Arc, Mutex},
+};
+
```
Comment (TimeEngineer) [inline src/storage/user_storage.rs:8]: Remove newline ?

**Review by TimeEngineer — CHANGES_REQUESTED** [review]

File: src/storage/mod.rs (hunk 31 above)
Comment (TimeEngineer) [reply src/storage/mod.rs]: Or we could avoid the `Result`, with a function `LocalManifest -> into_py_object` and parse `FileOrFolder` and `UserOrWorkspace` into `LocalManifest`

File: oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs [hunk 33]
```diff
@@ -63,54 +107,69 @@ pub struct WorkspaceStorage {
...
+    /// (We don't rely on [ManifestStorage]'s cache since it can be cleared).
+    workspace_manifest_copy: Mutex<LocalWorkspaceManifest>,
 }
 
 impl WorkspaceStorage {
-    pub fn new(
+    pub async fn new(
         // Allow different type as Path, PathBuf, String, &str
-        data_base_dir: impl AsRef<Path>,
+        data_base_dir: impl AsRef<Path> + Send,
```
[the remark this answers is not in the document]
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs:119]: That way the future is Send

File: src/storage/mod.rs (hunk 31 above)
Comment (FirelightFlagboy) [reply src/storage/mod.rs]: Should be done now :)

File: oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs [hunk 34]
```diff
@@ -185,13 +231,33 @@ impl WorkspaceStorage {
...
+        }
+    }
+
+    pub async fn load_file_descriptor(&self, fd: FileDescriptor) -> FSResult<LocalFileManifest> {
+        let entry_id = self
+            .open_fds
+            .lock()
+            .expect("Mutex is poisoned")
+            .get(&fd)
+            .cloned()
```
[the remark this answers is not in the document]
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs:255]: Yes I can, I don't have the reflex for that :shrug:

File: oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs [hunk 35]
```diff
@@ -201,197 +267,343 @@ impl WorkspaceStorage {
...
+        .await?;
+    manifest_storage.clear_memory_cache(true).await?;
+    manifest_storage.close_connection();
+
+    Ok(())
+}
+
 #[cfg(test)]
 mod tests {
+    #![allow(clippy::await_holding_lock)]
```
[the remark this answers is not in the document]
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs:589]: done

File: src/storage/user_storage.rs (hunk 32 above)
Comment (FirelightFlagboy) [reply src/storage/user_storage.rs:8]: I can but we don't have any format rule on import grouping (still unstable)

File: oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs (hunk 33 above)
[the remark this answers is not in the document]
Comment (TimeEngineer) [reply oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs:119]: which future ? can you be more precise ?

[the remark this answers is not in the document]
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs:119]: the `WorkspaceStorage::new` is an async function meaning it's a future

File: oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs [hunk 36]
```diff
@@ -201,197 +267,343 @@ impl WorkspaceStorage {
...
-                self.workspace_id,
-                LocalManifest::Workspace(manifest),
-                false,
-                None,
-            )?;
+    async fn load_workspace_manifest(
+        manifest_storage: &ManifestStorage,
+        workspace_id: EntryID,
+        device: &LocalDevice,
+    ) -> FSResult<LocalWorkspaceManifest> {
```
[the remark this answers is not in the document]
Comment (TimeEngineer) [reply oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs:361]: Is it used only for the instanciation ? (private function)

File: oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs [hunk 37]
```diff
@@ -201,197 +267,348 @@ impl WorkspaceStorage {
...
+    manifest_storage.clear_memory_cache(true).await?;
+    manifest_storage.close_connection();
+
+    Ok(())
+}
+
 #[cfg(test)]
 mod tests {
+    // TODO:
+    // We need to allow `await_holding_lock` because we the `Locker` interface that force us to use sync mutex.
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs:590]: because we the locker ?

File: oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs [hunk 38]
```diff
@@ -356,96 +468,370 @@ impl BlockStorage {
...
-        instance.create_db()?;
+        instance.create_db().await?;
+        instance.load_remanence_flag().await?;
         Ok(instance)
     }
 }
 
+// TODO: Remove it !
+// We would need to refactor the storage later.
+// We would combine the `manifest + chunk` storage that both use the `data` database and leet `block storage` on it's own.
```
Comment (TimeEngineer) [inline oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs:481]: typo: `let`

Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/chunk_storage.rs]: done

File: oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs (hunk 37 above)
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs]: done

**Review by TimeEngineer — APPROVED** [review]

File: .github/workflows/ci.yml [hunk 39]
```diff
@@ -324,7 +324,7 @@ jobs:
           && startsWith(matrix.os, 'macos-') != true
         # Note: using `--numprocesses 1` force pytest to print the test that it will be executing
         # This is usefull to pinpoint exactly which test in blocking.
-        run: poetry run pytest ${{ env.pytest-base-args }} tests --runmountpoint --runslow --rungui -m gui --numprocesses 1
+        run: poetry run pytest ${{ env.pytest-base-args }} tests --runmountpoint --runslow --rungui -m gui --numprocesses 1 -s
```
Comment (TimeEngineer) [inline .github/workflows/ci.yml:327]: Remove -s when ready

**Review by TimeEngineer — CHANGES_REQUESTED** [review]

File: oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs (hunk 36 above)
[the remark this answers is not in the document]
Comment (FirelightFlagboy) [reply oxidation/libparsec/crates/core_fs/src/storage/workspace_storage.rs:361]: Yes, (it's a private static method)

**Review by TimeEngineer — APPROVED** [review]

File: tests/core/gui/test_main_window.py [hunk 40]
```diff
@@ -208,96 +226,103 @@ def _folder_ready():
...
+async def test_link_file_invalid_path(
+    aqtbot,
+    autoclose_dialog,
+    logged_gui_with_files: LoggedGuiWithFiles,
+    toggle_timestamp: bool,
+):
     logged_gui, w_w, f_w = logged_gui_with_files
     await f_w.workspace_fs.sync()
 
-    with freeze_time(DateTime.now().add(seconds=1)):
```
Comment (TimeEngineer) [inline tests/core/gui/test_main_window.py:277]: Why ?

**Review by TimeEngineer — CHANGES_REQUESTED** [review]

File: tests/core/gui/test_main_window.py (hunk 40 above)
Comment (FirelightFlagboy) [reply tests/core/gui/test_main_window.py:277]: Because I can that's why :wink: 

That simplify the test, here the `freeze_time` serve no purpose

Comment (TimeEngineer) [reply tests/core/gui/test_main_window.py:277]: What did you change to solve the timeout ?

Comment (FirelightFlagboy) [reply tests/core/gui/test_main_window.py:277]: nothing :shrug: I can't reproduce it

**Review by TimeEngineer — APPROVED** [review]

**Review by touilleMan — APPROVED** [review]
👍 🥇 🎉 🍾
