### PR TITLE
[MS] Fixed global timeouts and error handling on org creation

### LINKED ISSUE #8564: Improve error message (user failed to create an organization)
Image

### PR DESCRIPTION
**Pull request by Max-7**
Closes #8564 

- [X] Keep changes in the pull request as small as possible
- [X] Ensure the commit history is sanitized
- [X] Give a meaningful title to your PR
- [X] Describe your changes

### CODE REVIEW

File: client/src/views/organizations/creation/CreateOrganizationSaas.vue [hunk 1]
```diff
@@ -210,10 +217,18 @@ async function onCreateClicked(): Promise<void> {
...
+      } else if (response.status === CONNECTION_ERROR_STATUS) {
+        currentError.value = 'CreateOrganization.errors.offline';
+      } else {
+        window.electronAPI.log('error', `Failed to create Saas organization, unhandled error ${response.errors}`);
+        currentError.value = {
+          key: 'CreateOrganization.errors.generic',
+          data: { reason: 'Unknown' },
+        };
       }
       step.value = Steps.Summary;
```
Comment (Ironicbay) [inline client/src/views/organizations/creation/CreateOrganizationSaas.vue:229]: This is already set in `onCreationError()`

**Review by Ironicbay — APPROVED** [review]
