### PR TITLE
[MS] hide last step cancel button

### LINKED ISSUE #9670: [🐛 | Bug]: Cancel button still displayed in the last step of `Copy workspace role` modal
### Parsec version tested on:

3.3.0-rc.6

### Platforms tested on:

Linux

### Bug description:

At the last step of the `Copy workspace role` modal, after applying the change, the cancel button is still visible where it should not since the action is already finished.

Clicking on the button seems to do nothing (except closing the modal)

### Relevant output:

Image

### PR DESCRIPTION
**Pull request by fabienSvtr**
## Describe your changes

image

## Checklist

Before you submit this pull request, please make sure to:

- [ ] Keep changes in the pull request as small as possible
   
- [ ] Ensure the commit history is sanitized
   
- [ ] Give a meaningful title to your PR
- [ ] Describe your changes
   
- [ ] Link any related issue in the description
   
- [ ] Link any dependent pull request in the description

closes #9670

### CODE REVIEW

File: client/src/views/users/BulkRoleAssignmentModal.vue [hunk 1]
```diff
@@ -131,6 +131,7 @@
             fill="clear"
             size="default"
             @click="cancel"
+            v-if="showCloseButton"
```
Comment (Ironicbay) [inline client/src/views/users/BulkRoleAssignmentModal.vue:134]: Why not just `v-if="currentPage !== Steps.Summary"` ?
