### PR TITLE
Set `volname` option in MacOS to set the volume name

### LINKED ISSUE #8842: [🐛 | Bug]: macOS mountpoint not using workspace name
### Parsec version tested on:

3.1.1-a.0

### Platforms tested on:

MacOS

### Bug description:

Mountpoint in macOS are not using the workspace name as volume/folder name but instead it's displayed as `macFuse volume N (Parsec Helper (Renderer))`

### Relevant output:

image

### PR DESCRIPTION
**Pull request by FirelightFlagboy**
Closes #8842

### CODE REVIEW

File: libparsec/crates/platform_mountpoint/src/unix/mount.rs [hunk 1]
```diff
@@ -150,10 +153,8 @@ impl Drop for Mountpoint {
 // changes on the mountpoint path.
 fn create_suitable_mountpoint_dir(
     base_mountpoint_path: &std::path::Path,
-    ops: &WorkspaceOps,
+    name: &EntryName,
```
Comment (mmmarcos) [inline libparsec/crates/platform_mountpoint/src/unix/mount.rs:156]: I'd keep `workspace_name` to better communicate the intent
```suggestion
    workspace_name: &EntryName,
```

**Review by mmmarcos — APPROVED** [review]
LGTM. Just a minor suggestion
