### PR TITLE
Move list_files out of platform_device_loader to platform_filesystem.

### LINKED ISSUE #12004: List file recursively and matching on extension
<details>

<summary>Native & Web specific</summary>

Native:

- `list_available_device`: https://github.com/Scille/parsec-cloud/blob/1c8e6cc753058f403ac632d4610d9d6a0839f43f/libparsec/crates/platform_device_loader/src/native/mod.rs#L64-L93
- `list_pending_local`: https://github.com/Scille/parsec-cloud/blob/1c8e6cc753058f403ac632d4610d9d6a0839f43f/libparsec/crates/platform_device_loader/src/native/mod.rs#L683-L697
- ListPkiLocalPendingError:
  - StorageNotAvailable
  - Internal
- ListAvailableDeviceError:
  - StorageNotAvailable
  - Internal  

Web:

- `list_file_entries`: https://github.com/Scille/parsec-cloud/blob/1c8e6cc753058f403ac632d4610d9d6a0839f43f/libparsec/crates/platform_device_loader/src/web/internal.rs#L60-L111
- ListFileEntriesError:
  - CastError
  - AwaitPromiseError
  - DomExceptionError
  - NotFoundError
  - NotADirectory

</details>

Normalized error:

- StorageNotAvailable
- InvalidParent (root/parent path is not a folder)
- ParentNotFound (root/parent directory not found)
- Internal (other specific errors)

Normalized function:

List file that match the given extension

```rust
pub async fn list_files(root_dir: &Path, extension: impl AsRef<OsStr> + std::fmt::Display) -> Result<Vec<PathBuf>, ListFilesError>
{
  todo!()
}
```

### PR DESCRIPTION
**Pull request by AureliaDolo**
Fix #12004

### CODE REVIEW

File: libparsec/crates/platform_filesystem/tests/units/list.rs [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    if path_exists {
+        std::fs::create_dir(tmp_path.join("devices")).unwrap();
+    }
+
+    let files = list_files(&tmp_path, "fake").await.unwrap();
+    p_assert_eq!(files, Vec::<PathBuf>::new());
+}
+
+#[parsec_test]
+async fn list(tmp_path: TmpPath) {
```
Comment (AureliaDolo) [inline libparsec/crates/platform_filesystem/tests/units/list.rs:35]: todo add paths to ignore (with another extension)

File: libparsec/crates/platform_filesystem/src/native/list.rs [hunk 2]
```diff
@@ -1 +1,61 @@
...
+    extension: impl AsRef<OsStr> + std::fmt::Display,
+) -> Result<Vec<PathBuf>, ListFilesError> {
+    log::debug!(
+        "Listing file entries in {} with extension {extension}",
+        root_dir.display()
+    );
+
+    let mut files = Vec::new();
+    let dir = root_dir;
+    let dirs_to_explore = Rc::new(Mutex::new(Vec::from([dir.to_path_buf()])));
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_filesystem/src/native/list.rs]: **issue:** Use `Arc` over `Rc` here since with use tokio runtime with multiple thread worker

File: libparsec/crates/platform_filesystem/src/native/list.rs [hunk 3]
```diff
@@ -1 +1,61 @@
...
+    while let Some(dir) = {
+        let mut handle = dirs_to_explore.lock().await;
+        let res = handle.pop();
+        drop(handle);
+        res
+    } {
+        log::trace!("Exploring directory {}", dir.display());
+        let mut entries_stream = match tokio::fs::read_dir(&dir).await {
+            Ok(v) => v,
+            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_filesystem/src/native/list.rs]: **issue:** The issue indicate to return `ParentNotFound` in that case

File: libparsec/crates/platform_filesystem/src/native/list.rs [hunk 4]
```diff
@@ -1 +1,61 @@
...
+                return Err(ListFilesError::StorageNotAvailable);
+            }
+        };
+        while let Some(entry) = entries_stream.next_entry().await.unwrap_or_default() {
+            // could not get metadata, ignore entry
+            let Ok(metadata) = entry.metadata().await else {
+                continue;
+            };
+            let path = entry.path();
+            if metadata.is_dir() && path != dir {
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_filesystem/src/native/list.rs]: **issue:** The condition `path != dir` is always true

File: libparsec/crates/platform_filesystem/src/native/list.rs [hunk 5]
```diff
@@ -1 +1,61 @@
...
+                log::trace!("New directory to explore: {}", path.display());
+                dirs_to_explore.lock().await.push(path);
+            } else if metadata.is_file() && path.extension() == Some(extension.as_ref()) {
+                files.push(path);
+            } else if metadata.is_file() {
+                log::trace!("ignoring file at {path:?}")
+            }
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_filesystem/src/native/list.rs]: **nitpick:** I would have put the extension check in an nested `if else` to not check multiple time if the file is a file

File: libparsec/crates/platform_filesystem/src/lib.rs [hunk 6]
```diff
@@ -123,6 +123,33 @@ pub async fn load_file(path: &Path) -> Result<Bytes, LoadFileError> {
...
+    native::list_files(root_dir, extension).await
+}
+
+#[cfg(target_arch = "wasm32")]
+pub async fn list_files(
+    root_dir: &Path,
+    extension: impl AsRef<OsStr> + std::fmt::Display,
+) -> Result<Vec<PathBuf>, ListFilesError> {
+    web::list_files(root_dir, extension).await
+}
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_filesystem/src/lib.rs]: **issue:** Instead of duplicating the function definition, we should just rename the platform modules:

```rust
#[cfg(not(target_arch = "wasm32"))]
#[path = "native/mod.rs"]
mod platform;

#[cfg(target_arch = "wasm32")]
#[path = "web/mod.rs"]
mod platform;
```

File: libparsec/crates/platform_filesystem/tests/units/list.rs [hunk 7]
```diff
@@ -0,0 +1,104 @@
...
+async fn list_no_files(
+    tmp_path: TmpPath,
+    #[case]
+    #[cfg_attr(target_arch = "wasm32", expect(unused_variables))]
+    path_exists: bool,
+) {
+    #[cfg(not(target_arch = "wasm32"))]
+    if path_exists {
+        std::fs::create_dir(tmp_path.join("devices")).unwrap();
+    }
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_filesystem/tests/units/list.rs]: **issue:** We want to do something similar to `libparsec/crates/platform_device_loader/tests/units/utils.rs` to also test the web part correctly

File: libparsec/crates/platform_filesystem/Cargo.toml [hunk 8]
```diff
@@ -15,6 +15,8 @@ workspace = true
 thiserror = { workspace = true }
 anyhow = { workspace = true }
 libparsec_types = { workspace = true }
+libparsec_platform_async = { workspace = true }
+log = { workspace = true }
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_filesystem/Cargo.toml:19]: **chore:** Those dependencies are already listed in that file ;)

File: libparsec/crates/platform_filesystem/src/native/list.rs (hunk 4 above)
Comment (AureliaDolo) [reply libparsec/crates/platform_filesystem/src/native/list.rs]: I add the issue of dir being re added to the dirs to explore, and so it was looping indefinitely. But it seems to work now

File: libparsec/crates/platform_filesystem/src/native/list.rs (hunk 3 above)
Comment (AureliaDolo) [reply libparsec/crates/platform_filesystem/src/native/list.rs]: That would be a breaking-ish changes, adding a log instead

File: libparsec/crates/platform_filesystem/src/native/list.rs [hunk 9]
```diff
@@ -1 +1,69 @@
...
+    } {
+        log::trace!("Exploring directory {}", dir.display());
+        let mut entries_stream = match tokio::fs::read_dir(&dir).await {
+            Ok(v) => v,
+            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
+                log::info!(
+                    "Path {} not found while attempting to list entries",
+                    dir.display()
+                );
+                return Ok(Vec::new());
```
Comment (FirelightFlagboy) [inline libparsec/crates/platform_filesystem/src/native/list.rs]: **todo:** Should just skip that folder and process the remaining
